### ISSUE TITLE
Command Return does not work

### ISSUE THREAD

**Issue by aaronrolls** [godbout/Wooshy.docs#10]
Command Return results in an error beep and does not preform a command click.

**Comment by fennelcakes** [comment]
I'm on OS X 12.4 and I'm not getting these error beeps. Going to upgrade to 12.5 and see if anything breaks. Could you describe how to replicate what you're getting?

For me, e.g. in Obsidian, where Cmd+Return creates a Markdown checkbox or checks it off, Wooshy replicates that behavior.
In Firefox, when Wooshy highlights over a link, Cmd+Return opens it in a new window while leaving the focus in the current window, as Cmd+Click with a mouse would.
If I Cmd+Return a highlighted Dock item with Wooshy, it opens a Finder window and Finder highlights the corresponding app.
So, all good here as far as Cmd Click.

**Comment by aaronrolls** [comment]
I am also on OS X 12.4. I tried all that you suggested and I still get the error beep. But cmd clicking works as it should.

**Comment by aaronrolls** [comment]
works on 1a2
