### ISSUE TITLE
not working on Adobe After Effects

### ISSUE THREAD

**Issue by Soft-Bred** [godbout/Wooshy.docs#100]

**Comment by godbout** [comment]
will check. thanks.

**Comment by godbout** [comment]
i'm going to test After Effects later today. i'll get the 7 days free trial sub. so it'd be great if we use those 7 days to make sure things are working according to expectations. i'll probably test today, and make a release very soon after. then you can test and i can investigate more if there's issue, as long as the trial is still valid.

**Comment by godbout** [comment]
complete custom UI. absolutely no Accessibility work done. (not surprising. they probably develop their own stuff so that they can port on any OS.) we'll get nothing from it, sorry.

https://user-images.githubusercontent.com/121373/209382674-06eec382-404d-45b5-b71b-42c0106e2bd0.mp4

**Comment by Soft-Bred** [comment]
Damn, disappointing. Stupid Adobe.

**Comment by godbout** [comment]
@Soft-Bred just in case you find any tool that can do something lemme know. i doubt that you will but i'm also not a djeenius so i may be missing something.
