### ISSUE TITLE
Using caps lock as the trigger key

### ISSUE THREAD

**Issue by srikat** [godbout/Wooshy.docs#103]
Looking for a way to have the caps lock key bring up Wooshy AND disable the caps lock functionality. Anyone knows how to?

I tried the free Hyperkey app but am not sure how to configure it for this purpose..

**Comment by godbout** [comment]
> Looking for a way to have the caps lock key bring up Wooshy AND disable the caps lock functionality. Anyone knows how to?

there's several ways. you could:
1. use [Karabiner-Elements](https://karabiner-elements.pqrs.org). this is a virtual keyboard driver, so this is very low level and you can remap anything you want, including the `caps lock` key which is usually not accessible from higher level frameworks. KE is pretty powerful. you can play with the key being pressed, or held, for how long, etc.
2. use the native macOS solution: you can remap `caps lock` to any other modifier, and escape. screenshot coming in the next comment.

**Comment by godbout** [comment]
<img width="827" alt="Screenshot 2023-01-01 at 12 23 04" src="https://user-images.githubusercontent.com/121373/210160955-a91c4034-bbc5-4829-ae3b-c908567df800.png">

**Comment by godbout** [comment]
> Looking for a way to have the caps lock key bring up Wooshy AND disable the caps lock functionality. Anyone knows how to?

your best bet is [Karabiner-Elements](https://karabiner-elements.pqrs.org). it adds a virtual keyboard driver to macOS, it's very low level, so you can do pretty much whatever you want. you can remap `caps lock` to any other hotkey. set that hotkey for Wooshy, and `caps lock` will activate Wooshy. there's 0 delay as it's a keyboard driver, not like other tools like Hammerspoon. and it's so powerful that if you wanted to, you can launch Wooshy with a quick press on `caps lock`, but do something else totally different with a long press. free and open source, also highly considering sponsoring its [creator](https://github.com/tekezo).

**Comment by godbout** [comment]
i actually do use KE myself to trigger a hotkey that is already taken by the system for Scrolla. here's the json rule for KE:

```json
                "rules": [
                    {
                        "manipulators": [
                            {
                                "description": "change control command space to option command space",
                                "from": {
                                    "key_code": "spacebar",
                                    "modifiers": {
                                        "mandatory": [
                                            "left_control",
                                            "left_command"
                                        ]
                                    }
                                },
                                "to": [
                                    {
                                        "key_code": "spacebar",
                                        "modifiers": [
                                            "left_option",
                                            "left_command"
                                        ]
                                    }
                                ],
                                "type": "basic"
                            }
                        ]
                    }
                ]
```

you could tweak it to change `caps lock` to whatever hotkey you need. you can see more from the [KE documentation](https://karabiner-elements.pqrs.org/docs/manual/).

**Comment by godbout** [comment]
working? if yes, i think we can close the issue. trying to keep the repo clean. thanks!

**Comment by srikat** [comment]
As this has nothing to do with your software directly, you may go ahead and close.

I've mapped it to the left Ctrl key to keep it simple using BetterTouchTool.
