### ISSUE TITLE
not working on Texts

### ISSUE THREAD

**Issue by roelvangils** [godbout/Wooshy.docs#106]
https://texts.com 🙂

**Comment by godbout** [comment]
strange. it was supported since day one. got a bunch of emails back and forth with the founder. will check.

**Comment by godbout** [comment]
works fine here:

https://user-images.githubusercontent.com/121373/211198311-7a40e6dc-9661-4756-b140-b53ac3371f06.mp4

what version are you using?

**Comment by godbout** [comment]
using latest here, 0.74.1.
also there's two types of Accessibility in Texts, somehow one native, and one Electron. the Electron was added in Wooshy a8 (https://github.com/godbout/Wooshy.docs/issues/7), but better use the native Accessibility from Texts options.

**Comment by godbout** [comment]
try maybe changing this option and see if it helps:

<img width="774" alt="Screenshot 2023-01-08 at 21 29 59" src="https://user-images.githubusercontent.com/121373/211198666-6577a382-4bb2-42f9-9d8e-15dd49c68177.png">

**Comment by godbout** [comment]
@roelvangils any update from your side? thanks.

**Comment by roelvangils** [comment]
It worked after I enabled this setting:

![Run with Safari renderer Use a different rendering engine that consumes less CPU and RAM.](https://user-images.githubusercontent.com/103744/213914848-b2bcfa2d-04e5-47f5-86bc-d36d41866c60.png)

**Comment by godbout** [comment]
yes. that's the screenshot i shared 😅 great. thanks.
