### ISSUE TITLE
Let Wooshy treat different targets differently (Web browser)

### ISSUE THREAD

**Issue by hasantahir** [godbout/Wooshy.docs#107]
Wooshy has settings to change the Scope of the search. However, on webpages, the tabs and bookmarks are also searched to find a given target. It would be great if we can ignore the Tabs, bookmarks etc. and focus on the web pages.

Thanks

**Comment by godbout** [comment]
> It would be great if we can ignore the Tabs, bookmarks etc. and focus on the web pages.

ok so i'm noticing the bookmarks thing now. so basically, do you want Wooshy to only focus on the content of the web page and ignore all the rest? even like extensions, etc.? i'm personally bothered by the Address Bar. not by the tabs as i barely use any, and i'm using Safari compact tab mode. but i trigger extensions with Wooshy. seems like or i need to approach each specific thing separately, or if only allow for the web content but i think it's gonna be an issue for a lot of people.

**Comment by tsch0hnny** [comment]
I'm not trying to push a browser on you, but I solved this issue by using the Arc Browser where I usually have my tabs hidden (you can show them with `cmd` + `s`)

**Comment by hasantahir** [comment]
Thanks G!

Noticed that the new version locks Wooshy and pressing the escape key doesn't close it. Have to click the mouse somewhere to escape from the app.

**Comment by godbout** [comment]
> Noticed that the new version locks Wooshy and pressing the escape key doesn't close it. Have to click the mouse somewhere to escape from the app.

wow that sounds really bad. haven’t noticed that. will let you know asap once i’m back on a computer (in an hour or two).

**Comment by hasantahir** [comment]
Sorry for flaring this up. This was caused by another app, Keyboard Cowboy.

**Comment by godbout** [comment]
was just gonna answer that i wasn't able to reproduce here 🤣️

**Comment by godbout** [comment]
reopening here because there's still a lot of work, digging and exploration to be done to have a proper "Web content focus only" mode to handle all the browsers. thanks @hasantahir as always!
