### ISSUE TITLE
not working in lens 

### ISSUE THREAD

**Issue by roryfahy** [godbout/Wooshy.docs#112]
the only thing that highlights are the three buttons on top left of app 
<img width="91" alt="image" src="https://user-images.githubusercontent.com/42627486/215294642-526f1db9-b952-48d2-8a54-de9d7f7424c0.png">

**Comment by godbout** [comment]
there's several apps called `lens`. which one you're talking about?

**Comment by godbout** [comment]
https://github.com/lensapp/lens?

**Comment by godbout** [comment]
decided it was the kubernete lens app. added in v7: https://github.com/godbout/Wooshy.docs/releases/tag/7

**Comment by roryfahy** [comment]
@godbout yes, it was k8s lens thank you. sorry for not replying sooner, I need to figure out how to set my GitHub notifications better
