### ISSUE TITLE
Ignore diacritics

### ISSUE THREAD

**Issue by ldebritto** [godbout/Wooshy.docs#113]
It would be lovely if The Input would match for characters regardless of diacritics or accents, such as é è, etc.

Now, if I want to reach a target with `Olívia` I need to enter the corresponding character `olí`. If I hit `oli` it will not match.

**Comment by godbout** [comment]
that is very fair. also because you have a nice profile picture, i'll do it.

**Comment by godbout** [comment]
> The Input

also man: ❤️❤️❤️

**Comment by ldebritto** [comment]
I missed this The Input**™️** 🤣

**Comment by godbout** [comment]
how complicated do we make it?

https://user-images.githubusercontent.com/121373/217726022-ed2052d5-c33f-4cc4-b6a2-dc4e621a7573.mp4

easy way is to remove any diacritic. simple. but if you want to _enforce_ a search with diacritics, it wouldn't work hehe. reminds me a bit of the magic search in Vim, where lowercase letters match lowercases and uppercases but uppercases only match uppercases.

should we make it that complicated too? like if there's no diacritic, ignore. if there is, take in consideration?

**Comment by godbout** [comment]
probably best is to ignore diacritics all the time? like this:

https://user-images.githubusercontent.com/121373/217752936-6175f677-8cf4-427c-9231-712ad50424d8.mp4

other way would be to detect if there's a diacritic in a String, and change the behavior accordingly. but it's tricky. not that easy to detect (with Swift) apparently.

**Comment by godbout** [comment]
ignored in v7: https://github.com/godbout/Wooshy.docs/releases/tag/7
