### ISSUE TITLE
Support for Shift

### ISSUE THREAD

**Issue by caffo** [godbout/Wooshy.docs#114]
How hard would it be to add support to https://tryshift.com/? I use it every day for work.

**Comment by godbout** [comment]
seems it's somehow working if you hide Shift and show it again? see below:

https://user-images.githubusercontent.com/121373/217445219-171abfc4-529d-4313-b443-3131a3b24795.mp4

but that's just a quick fix for you to use it now. i'll make changes so that it works right away, without having to hide.

**Comment by godbout** [comment]
added in v7: https://github.com/godbout/Wooshy.docs/releases/tag/7
