### ISSUE TITLE
⎵ i cannot find this key to start wooshy

### ISSUE THREAD

**Issue by khanakia** [godbout/Wooshy.docs#118]
I have installed the whooshy and it says to use these keys combination`⇧⌘⎵` to start wooshy. But i cannot find this `⎵` key on keyboard

**Comment by godbout** [comment]
`⎵` is the standard icon for the spacebar. but you can replace the hotkey by whatever you want in the Settings :))

**Comment by khanakia** [comment]
Thanks. This is the app I was looking for months man. 
I tried many apps before that but this one you nailed it 💯

**Comment by godbout** [comment]
great to hear! it's in constant development. so feel free to report things that come to your mind, and maybe some will get implemented. enjoy till then.

**Comment by khanakia** [comment]
I have one more question how do i click the Toggle button ?

![Screenshot 2023-02-25 at 10 57 53 AM](https://user-images.githubusercontent.com/2174170/221340144-79a275cf-dfe4-49e1-a944-e0bb857406df.png)

**Comment by godbout** [comment]
macOS might be using `switch`? when you don't know what are the terms to target something, just move your mouse around macOS. Wooshy will show you what terms you can use for each target. yeah currently you need to use the mouse 😂 thinking of a better UX for the future.

**Comment by godbout** [comment]
hmm. multiple monitor has been supported for a long time now. are you sure the window you're targeting is active?

see https://github.com/godbout/Wooshy.docs/issues/47 and https://github.com/godbout/Wooshy.docs/issues/90 for more info.

if it still doesn't work, please lemme know what is your `Displays have separate Spaces` macOS setting. you can see what i'm talking about from the above issues. thanks.

**Comment by khanakia** [comment]
Yes, it works with Active monitor. I meant I want to work it with an Inactive monitor too.

As i have to switch often between monitors for my work.

**Comment by godbout** [comment]
i don't get what you mean. Wooshy works on the active window. it doesn't matter on which monitor this window is. the window can be split onto several monitors, and Wooshy still targets it correctly.

**Comment by khanakia** [comment]
as i have 2 monitors so each one has a kinda active window. So i wanted to make it work the same way on the window on the second monitor which is not the active window but it's on the top.

Or 

if i have 2 windows side by side i want to make it work on either of the windows regardless of active window.

**Comment by godbout** [comment]
> as i have 2 monitors so each one has a kinda active window. 

that's not possible. this is where the confusion comes from. under macOS, you can only have one "active" (focused) window. and Wooshy can grab info only from that window.

you can easily bring any window to the foreground with my Alfred Workflow: https://github.com/godbout/WooshyWindowToTheForeground
if you use other tools like Raycast, maybe they have plugins. not sure. the Alfred workflow above lists all visible windows and allow you to bring them up front so that you can blast Wooshy on them. good luck.
