### ISSUE TITLE
Not working on BBEdit

### ISSUE THREAD

**Issue by ChristinWhite** [godbout/Wooshy.docs#122]
Oddly, Wooshy doesn't seem to know how to interact with [BBEdit](https://www.barebones.com/products/bbedit/) which I can't imagine isn't a native app.

**Comment by godbout** [comment]
don't know if this will speak to you, but yes, BBEdit is not accessible:

https://user-images.githubusercontent.com/121373/225815799-c7f78676-10ea-4dd9-a380-483384fa66eb.mp4

they seem to be having their own container, and drawing stuff inside. so non native elements, and they don't make their own stuff accessible. so nothing much Wooshy can do here sorry.

**Comment by ChristinWhite** [comment]
How strange, thanks for looking into it!

**Comment by godbout** [comment]
no worries.
