### ISSUE TITLE
Sequence based activation like KindaVim

### ISSUE THREAD

**Issue by Josh-Piper** [godbout/Wooshy.docs#127]
Would love for the exact same activation methods that kindavim allows for within Wooshy and Scrolla

<img width="438" alt="image" src="https://github.com/godbout/Wooshy.docs/assets/35862340/4403a3f8-a744-48a7-b51f-59ede99faab6">

<img width="329" alt="image" src="https://github.com/godbout/Wooshy.docs/assets/35862340/2910068e-4b23-4421-9dae-72d918aee995">

**Comment by godbout** [comment]
interesting. nice. fair.

just out of curiosity, what sequence would you use for all those apps?

**Comment by Josh-Piper** [comment]
Mhmm, still a work in progress but I have s+d set for KindaVim since it is on the homerow. I still have the muscle reflex to hit escape though, so it takes me a couple seconds to remember to use the sequence.

My current setup for replicating the sequence has been using Karabiner elements mappings of
Scrolla: a + s(scrolla)
Kindavim: s + d (not idea why I stumbled on this)
Wooshy: a + w(hooshy)

How do you have yours set up? For the three apps? Interested in how you have your muscle memory tied to it all!

**Comment by godbout** [comment]
> My current setup for replicating the sequence has been using Karabiner elements mappings of Scrolla: a + s(scrolla) Kindavim: s + d (not idea why I stumbled on this) Wooshy: a + w(hooshy)

n🧊️

> How do you have yours set up? For the three apps? Interested in how you have your muscle memory tied to it all!

coz i'm a dick i've just set my own setup as default for the apps 🤣️🤣️🤣️

`escape` for kV. `shift command space` for Wooshy. `control command space` for Scrolla. strangely tho, i need Karabiner to get Scrolla to works on my MBP, but not on my mini.

**Comment by godbout** [comment]
i'm working on a `dyslexic` mode for the sequence in kV, before adding everything to Wooshy and Scrolla. but checking the sources i remembered that Scrolla uses another way to grab key events, that allow users to use Scrolla in SecureInput (passwords, etc.) so adding the sequence in Scrolla means 1) a big rewrite/tests 2) losing some functionality.

**Comment by godbout** [comment]
btw @Josh-Piper you can already do what you wanna have with tools like `Hammerspoon` for sure, and maybe `Karabiner-Elements` too. you could ask `Hammerspoon` to send your hotkey once a sequence is triggered. easy peasy.

**Comment by Josh-Piper** [comment]
Yup thats true. I'll take a look into hammerspoon

**Comment by godbout** [comment]
i'm planning to add it natively to Wooshy, because it's using the same tap event system as kV. but for Scrolla it's a different one, to be able to handle the scrolling on long key presses. so it's probably gonna be much harder there, and may need a complete Scrolla rewrite.

**Comment by godbout** [comment]
@Josh-Piper i'm gonna start working on this. but curious: have you done it through Hammerspoon? if not, will you still use this in Wooshy natively? thanks.

**Comment by godbout** [comment]
i've decided not to integrate this into Wooshy and Scrolla. it does make sense for kV because a bunch of people use the traditional `jk` or `jj` to enter `Normal Mode`. i'm not aware tho of any other app that does this over a keyboard shortcut natively to start their app. this is doable with proper tools tho, like Karabiner-Elements and Hammerspoon. so i think when things start to get funky, people dig into those instead.

please reopen if you have good counter arguments 😂️
