### ISSUE TITLE
Toggle with URI

### ISSUE THREAD

**Issue by jannis-baum** [godbout/Wooshy.docs#133]
If we had the option to toggle Wooshy's Input (and Scrolla and kV🙈) with a URI, customization and scripting would get easier and cleaner! I, for example, use a combo of `u+i` to open Wooshy. To make this possible I have to set Wooshy to some random keybinding that never interferes (`cmd+f8`) and then use Karabiner to remap `u+i` to that. Much cleaner would be to just map `u+i` straight to something like `open -g wooshy://toggleInput`.

---

See [Apple's guide on URI schemes](https://developer.apple.com/documentation/xcode/defining-a-custom-url-scheme-for-your-app), it comes down to

1. setting up the `info.plist`
   ```xml
   <key>CFBundleURLTypes</key>
   <array>
     <dict>
       <key>CFBundleTypeRole</key>
       <string>Editor</string>
       <key>CFBundleURLName</key>
       <string>BUNDLE ID OF WOOSHY HERE</string>
       <key>CFBundleURLSchemes</key>
       <array>
         <string>wooshy</string>
       </array>
     </dict>
   </array>
   ```
2. catching it in your `App.swift`
   ```swift
   func application(_ application: NSApplication, open urls: [URL]) {
       guard let url = urls.first, url.absoluteString.hasPrefix("wooshy://toggleInput") else { return }
       // now toggle The Input
   }
   ```

**Comment by jannis-baum** [comment]
More benefits of this are that 

- it's possible to add separate URIs for toggle, open, and close
- we can pass information, e.g. give the option to open Wooshy with a given query like `open -g wooshy://openInput?query=myquery`
  ```swift
  func application(_ application: NSApplication, open urls: [URL]) {
      guard let url = urls.first, url.absoluteString.hasPrefix("synapse://openInput") else { return }
      let items = URLComponents(url: url, resolvingAgainstBaseURL: true)?.queryItems
      let query = items?.first(where: { $0.name == "query" })?.value
      // ensure input is open and set query if not nil
  }
  ```

**Comment by godbout** [comment]
:LOVE:

**Comment by godbout** [comment]
starting on this. very excited.

**Comment by godbout** [comment]
interesting. when i call the same code as with the keyboard shortcut but through an custom URL, Wooshy steals the current app "focus", which means it becomes useless. 🤔️

**Comment by godbout** [comment]
first call from hotkey, second call from URL:

https://github.com/godbout/Wooshy.docs/assets/121373/3c1edff7-2151-4f46-87b5-fbde64c27b09

**Comment by jannis-baum** [comment]
Oh, yes, when you just `open` a URI it will activate the responding app. Try `open -g`😁

**Comment by godbout** [comment]
oh 😅️

i tried at first through Safari but the same was happening. what about when you call from another app then? got too lazy to find the right way to call an URL from Hammerspoon. everything i look at their docs i'm having a migraine.

**Comment by godbout** [comment]
aww. works great with `open -g` 😂️

**Comment by godbout** [comment]
> (and Scrolla and kV🙈) with a URI

any chance you can describe also in their own repository what you would like to achieve with URIs in kV and Scrolla. sorry but coz i don't do automation (and i'm busy so no time to think about it) i have really no clear idea of what would be good to add 🤣️

**Comment by godbout** [comment]
got the thing done for Wooshy.

for the fine-tuning, i like expressive URLs so the `query` didn't do it :D

this is what i have currently:
1. `wooshy://openTheInput?with=hello`
2. `wooshy://closeTheInput`
3. `wooshy://toggleTheInput?with=hehe`

internally the input is called TheInput, because it's the only one in Wooshy 😂️

**Comment by godbout** [comment]
> They're perfect!!🤩 Excited to try them out😊

nice! thank you. i'm gonna see if i can add some unit tests (if necessary), then i'll make a release. most probably this week.

> Yes of course! Can open issues soon. But it's basically the same minus the `with` parameter, i.e. just so we can (de-)activate the apps without having to pretend to press a keybinding ^^

❤️

**Comment by godbout** [comment]
added in Ws15: https://github.com/godbout/Wooshy.docs/releases/tag/15

thank you!
