### ISSUE TITLE
See inspector without a mouse

### ISSUE THREAD

**Issue by jannis-baum** [godbout/Wooshy.docs#135]
The inspector is great to keep us from using a mouse... but we need a mouse to see it??🙈 Maybe you could show it for the currently selected target while command or something is held down

**Comment by godbout** [comment]
the irony.

i liked the idea that you have to use the mouse once so that you don't use it afterwards. so that reminds you that you have to be grateful for Wooshy 😂️😂️😂️

but yeah. need something better.

**Comment by jannis-baum** [comment]
Hahahah I like the idea😁

I only have a super old Apple mouse whose batteries ran out a few weeks ago and I refuse to buy new ones😂 So now it's 100% Wooshy with no compromises because using a mouse means I have to grab and open my laptop

**Comment by godbout** [comment]
what about pressing a key combination? i'm thinking something like `command ?` to toggle The Inspector on and off. i like the idea of just pressing a key modifier to show The Inspector while pressing but that requires another way to handle keyboard events ☹️

**Comment by jannis-baum** [comment]
Yes that works as well!

**Comment by godbout** [comment]
still in the plans to allow people to set their own custom mappings tho.

also have you seen this for Wooshy: https://github.com/godbout/Wooshy.docs/issues
any thoughts? i'm curious 😁️

**Comment by jannis-baum** [comment]
> also have you seen this for Wooshy: https://github.com/godbout/Wooshy.docs/issues
> any thoughts? i'm curious 😁️

Which issue exactly?🙈

**Comment by godbout** [comment]
🤦‍♂️️ that one 🤣️ : https://github.com/godbout/Wooshy.docs/issues/151

**Comment by godbout** [comment]
also i'm starting experimenting with that one: https://github.com/godbout/Scrolla.docs/issues/16

if you have anything to add and/or new, i'll be glad to read!

**Comment by roelvangils** [comment]
> also have you seen [this](https://github.com/godbout/Wooshy.docs/issues/151) for Wooshy
> any thoughts? i'm curious 😁️

Oh, I think that's a very nice idea. The person who came up with it is a genius!

**Comment by godbout** [comment]
> Oh, I think that's a very nice idea. The person who came up with it is a genius!

that guy is not even a subscriber 🤣️🤣️🤣️

**Comment by roelvangils** [comment]
Really? I thought my monthly subscription was ending on the 27th of August 😁 After that, I'll pay for one year ahead. Yes, I'm looking forward to it! Take my money, mister!

**Comment by godbout** [comment]
> Really? I thought my monthly subscription was ending on the 27th of August 😁 After that, I'll pay for one year ahead. Yes, I'm looking forward to it! Take my money, mister!

as far as Paddle is concerned you have canceled your subscription so even if you still have access to it for now you are now part of the bad guys. but of course they don't know Roel like i do hehehehehehehehehe ❤️🤣️

**Comment by roelvangils** [comment]
![a-man-in-a-red-shirt-is-standing-next-to-another-man-in-a-white-shirt-and-talking-to-him](https://github.com/user-attachments/assets/9b70f680-ca11-4f18-aaeb-f47cbe9bcdb8)

Yeah, look at us! ❤️

**Comment by godbout** [comment]
@jannis-baum working on this now. trying different workflows. once The Inspector 🕵️‍♂️️ shows up, what would you like to happen when/if you move Target:
1. The Inspector stays on the Target that you call him on
2. The Inspector disappears
3. The Inspector follows you to the new Target

i'm sure there's gonna be more questions later, but that's the first batch.

**Comment by jannis-baum** [comment]
I would say either 2. or 3. because 1. looks a bit like a it's bug and the inspector will never disappear again🙈

Between those two it's a bit hard to decide but I think I'd go for 3. because that not only serves the purpose of finding the name for one target but also allows you to "explore" more easily

**Comment by godbout** [comment]
oh yeah. does it make sense to keep The Inspector for the mouse then? less code is better code.

**Comment by godbout** [comment]
(also in some other news, working hard on the Scrolla and Wooshy custom key mapping. still far from the end solution but been spending weeks on that and making good progress! (means made a thousand discoveries and choices that get me closer to a proper solution))

**Comment by jannis-baum** [comment]
> oh yeah. does it make sense to keep The Inspector for the mouse then? less code is better code.

Hm. How does the whole thing work right now, as in how do you trigger the inspector to show up with the keyboard?

I would actually probably argue keeping the mouse way as well still makes sense. Because people already know that and it's also intuitive (as long as you don't think about it too hard lol)

**Comment by jannis-baum** [comment]
Oki yeah makes sense. I think from a pure UX perspective I'd leave the mouse option but if it was my code I'd probably favor the clean code over the UX and get rid of it haha. Probably fine if you write it in the top of the release notes

**Comment by godbout** [comment]
i was able to refactor the code so that it looks beautiful now AND i got rid of some local variables from my Event Tap which makes Wooshy even lighter 😍️😍️😍️ almost having an orgasm 🥹️🥹️🥹️ release expected soon.

**Comment by godbout** [comment]
done in https://github.com/godbout/Wooshy.docs/releases/tag/30
