### ISSUE TITLE
Wooshy Crashes in MS Outlook app

### ISSUE THREAD

**Issue by hasantahir** [godbout/Wooshy.docs#137]
Hi G!

After updating Microsoft Outlook to Version 16.77.1 (23091703), Wooshy crashes every time it is invoked inside the Outlook app. Haven't observed this behaviour in any other MS app (Word, PowerPoint, Excel etc.). I was on Wooshy v13 before updating to v15 and both versions crashed.

Crash reports below

[v13 - Wooshy-2023-09-27-122408.txt](https://github.com/godbout/Wooshy.docs/files/12762431/v13.-.Wooshy-2023-09-27-122408.txt)
[v15 - Wooshy-2023-09-29-091350.txt](https://github.com/godbout/Wooshy.docs/files/12762432/v15.-.Wooshy-2023-09-29-091350.txt)

**Comment by godbout** [comment]
will check. 

short story: been helping a local client for 1.5 months now (kindaVim and Wooshy don't pay the bills) and i'm stuck with Windows two afternoons a week. i go back home broken, and depressed LOL

**Comment by godbout** [comment]
well. just pinging AX info crashes. not sure if it's Apple's API that's buggy (on macOS 14? which one you're on?) or Outlook itself. it breaks all my apps.

**Comment by godbout** [comment]
infinite looping. basically because they're registering the Search Bar, which is a text field, as a child of itself... i have many exceptions in place to make sure Wooshy is fast and avoid those problems, but never had to with a text field... so, should be solvable, but will have to check for side effects. more on this later.

**Comment by hasantahir** [comment]
Thanks for your prompt replies like always. Wishing you a restful and nice weekend ☺️.

I have switched to MacOS 14. Haven't noticed this behaviour elsewhere.

**Comment by godbout** [comment]
> I have switched to MacOS 14. Haven't noticed this behaviour elsewhere.

yes, the issue is with Outlook and Microsoft, not Apple and the AX Framework this time 😂️

i'm gonna do a fix soon. hopefully releasing an update in a few hours.

**Comment by godbout** [comment]
please update to Ws16: https://github.com/godbout/Wooshy.docs/releases/tag/16
should fix the issue. thanks Hasan for reporting!

**Comment by hasantahir** [comment]
Awesome. Apologies for reporting this over your weekend. 

Thanks G!

**Comment by godbout** [comment]
my pleasure. and actually i work everyday, but more during weekends 🤣️
