### ISSUE TITLE
Copy (Cmd-C) not working on macOS Sonoma 14.0

### ISSUE THREAD

**Issue by tddschn** [godbout/Wooshy.docs#138]
Thank you so much for making the app!

I never used Wooshy on macOS versions earlier than Sonoma, and everything has been working great except the Cmd-C copy feature. 

When I press Cmd-C, I hear macOS playing the sound indicating the shortcut is not recognized (because there's nothing to select?) and the text of the primary target is not written to my clipboard.

Wooshy verison: `2828.15.0`
macOS: `14.0 23A344 x86_64`

**Comment by godbout** [comment]
works good here:

https://github.com/godbout/Wooshy.docs/assets/121373/2400bfca-7517-40bd-8b2c-785d763eaa50

any chance you haven't enabled the Setting?:

<img width="520" alt="Screenshot 2023-10-01 at 13 59 27" src="https://github.com/godbout/Wooshy.docs/assets/121373/459fa427-9377-4cd8-99f8-8ff152f9c798">

**Comment by tddschn** [comment]
Thank you for your help! 

Yeah I didn't enable it, thought it was enabled by defualt 😅

**Comment by godbout** [comment]
> Yeah I didn't enable it, thought it was enabled by defualt 😅

the feature didn't come with Wooshy 1. just to make sure, in the case where people would sometimes copy the content of The Input with `⌘c`, which would be weird but why not, i made it an optional Setting not enabled by default. might change in the future.

thanks and enjoy!
