### ISSUE TITLE
Exclude 🚥

### ISSUE THREAD

**Issue by roelvangils** [godbout/Wooshy.docs#14]
I'd like it if the 🚥 buttons could be excluded from the search (maybe as an option). When I type `in`, _minimise_ is the first button highlighted. But in most apps, I just want to go to _Inbox_ or something. I think most people use <kbd>⌘</kbd><kbd>M</kbd> anyway for minimising (and <kbd>⌘</kbd><kbd>W</kbd> for closing a window).

**Comment by godbout** [comment]
yes. i had the same "feeling" when i was developing Wooshy. i took a quick pass at it at the time but i've found two issues: 1) i removed them quickly through keywords and that would remove of course other targets that i wanted. so i would need to properly target the traffic lights with keyword + position + size maybe? a pain to get it to work in all setups. 2) i think i faced windows where `⌘W` wouldn't work but using Wooshy would 😃️ 

anyways. those were the issues at the time. i'll have a deeper look and see what i can do. thanks.

**Comment by godbout** [comment]
> 🚥

nice btw.

**Comment by godbout** [comment]
done in a5: https://github.com/godbout/Wooshy.docs/releases/tag/1a.5

sorry it took so long 🥺️☹️

**Comment by roelvangils** [comment]
![20220728_170244_Wooshy@2x](https://user-images.githubusercontent.com/103744/181571555-368755ed-bbd5-46e2-9208-fc6eb5346543.png)

**Comment by godbout** [comment]
enjoy. that was a great idea, thanks. i'm forbidding the traffic lights myself.
