### ISSUE TITLE
not working on Notion

### ISSUE THREAD

**Issue by red-mantis** [godbout/Wooshy.docs#144]
Wooshy doesn't seem to be able to work with the Notion app at all.

**Comment by godbout** [comment]
reported to the Notion team. they broke their AX. they don't care. they tell people to use their browser instead LMAO. there's another open issue about the topic so i'm gonna close that one: https://github.com/godbout/Wooshy.docs/issues/139

**Comment by godbout** [comment]
found a way. coming soon. (see https://github.com/godbout/Wooshy.docs/issues/139)
