### ISSUE TITLE
PDF Viewer in Chrome - Fit to Width

### ISSUE THREAD

**Issue by hasantahir** [godbout/Wooshy.docs#145]
Greetings G!

Due to the hit-and-miss nature of the `⌃ + \` keyboard shortcut to fit a PDF to display page, I rely on Wooshy twice to fit a PDF to width whilst viewing inside the Chrome web browser. Even when the keyboard shortcut seems to work, I have to do the fitting in a two-step process. 

Lately, I have noticed for my second attempt to reach the fit-to-width button, Wooshy ignores it. Moreover, the inspector also does not catch that particular UI element.

First Attempt is a success:
<img width="419" alt="SCR-20231211-kyqq" src="https://github.com/godbout/Wooshy.docs/assets/11236148/fd553676-8261-48ba-88ed-555c39c3b758">

The second attempt is not (note the icon changes too):
<img width="520" alt="SCR-20231211-kyto" src="https://github.com/godbout/Wooshy.docs/assets/11236148/f7a350d2-14ac-4ed3-8b28-aeb1f5a82976">

The UI description however remains the same: 
<img width="505" alt="SCR-20231211-kyva" src="https://github.com/godbout/Wooshy.docs/assets/11236148/904555f8-44cb-4901-8972-496cf4142240">

**Comment by godbout** [comment]
ok so i didn't have Chrome on my machines. i tried with Brave, which is using the same engine, and it works fine. i downloaded Chrome to give it a try, and it works fine also here... the `^\` shortcut works fine also every single time here. so i'm thinking: do you have any extension that maybe steals the shortcut? and maybe somehow fucks with the Accessibility, so that Wooshy can't find the UI Element? it would be nice to try without any extension and see if you're still having the issue.

**Comment by godbout** [comment]
you can start Chrome without the extensions from your terminal with: `open --new -a "Google Chrome" --args --disable-extensions`

**Comment by hasantahir** [comment]
Thanks for getting back. Strange that this is happening in the disabled extensions mode as well as the incognito mode with no extensions. Will check on the personal machine which doesn't have some restrictive analytics apps currently imposed on the work machine.

**Comment by godbout** [comment]
yeah please let me know. if you can also please try Brave and let me know. and also if you can let me know your Google's version on your work computer. anyways. let me know!

**Comment by hasantahir** [comment]
It works as expected on Brave (which by the way seems amazing). The effect may be the result of the added frills required for monitoring our work machines. 

Guess time to ditch Chrome.

Thanks as always.

**Comment by godbout** [comment]
> It works as expected on Brave (which by the way seems amazing). The effect may be the result of the added frills required for monitoring our work machines.

pretty strange.

Brave is using the same engine as Chrome. what you're gonna have different is all the stuff around. enjoy. haven't used Chrome myself for ages. Safari for day to day. Brave for dev hehe.
