### ISSUE TITLE
not working on Bitwarden

### ISSUE THREAD

**Issue by TCattd** [godbout/Wooshy.docs#16]
Ok.
Following this: https://github.com/godbout/Wooshy.docs/issues/15#issuecomment-1195590327
Found four more that i use here.

Bitwarden Desktop: https://bitwarden.com/download/

Thanks in advance for the time put on this ;)

**Comment by godbout** [comment]
> Thanks in advance for the time put on this ;)

hey, my pleasure. but ok just in case, to avoid a bad surprise in case you're not aware, this is gonna be a paid app 😃️ one coffee a month (see https://www.youtube.com/watch?v=-N6VwfQGrCU&t=178s and https://github.com/godbout/Wooshy.docs#license). the current alphas are valid for a month. betas probably something similar.

thanks for the report. will add soon.

**Comment by TCattd** [comment]
I'm aware ;)

**Comment by godbout** [comment]
sorry the README says 3.28 but actually it's 328. it's a massive cup of coffee:

![1D274907105562-today-big-mug-141029](https://user-images.githubusercontent.com/121373/181048337-ab43dd30-ca48-46b4-9273-63796fd04496.jpg)

**Comment by godbout** [comment]
added in a4: https://github.com/godbout/Wooshy.docs/releases/tag/1a.4
