### ISSUE TITLE
Slow on MailMate

### ISSUE THREAD

**Issue by aaronrolls** [godbout/Wooshy.docs#2]
It does work but it causes the app to be non responsive for a time.

**Comment by godbout** [comment]
will check. thanks.

**Comment by godbout** [comment]
so i've installed it. blazing fast.
then i added an account with tons of emails, still fast. of course slower as it needs to ping all UI elements, but still ok. see below:

https://user-images.githubusercontent.com/121373/180734257-0f4987ca-b76c-42ce-90f5-bb8d240b8a8b.mp4

any more info you can give me? does Wooshy work well on other apps? what becomes non responsive, Wooshy or MailMate?

**Comment by godbout** [comment]
for me both Wooshy and MailMate are responsive:

https://user-images.githubusercontent.com/121373/180734997-9f72d721-9e10-4133-bdcf-7224847e5cfa.mp4

**Comment by godbout** [comment]
didn't mean to close sorry, wrong manipulation with Wooshy 😂️

**Comment by godbout** [comment]
> Both become non responsive. Mailmate for much longer. It depends on the folder that I pick, but I tried it on my main one and mailmate has been unresponsive for over a minute and wooshy was unresponsive for about 10 seconds.

wow ok, that's not cool.

> In my main folder I have over 200,000 emails.

😅️

> It feels like it is trying to interact with every email, rather than the ones that are on screen.

Wooshy grabs the "visible elements", but it's up to each app to implement this properly. it is possible that MailMate returns ALL the emails. in that case nothing we can do. do you know about Vimac/Homerow/Shortcat? i'd be interested to see if you're having the same issue with those tools. if not then there's something i can do.

**Comment by godbout** [comment]
to give you an idea. on Finder. Wooshy grabbing only the visible elements vs Homerow that i think grabs all of them (i have a lot of files in Recents):

https://user-images.githubusercontent.com/121373/180749002-f7d355a5-b5a8-4d62-baeb-58071894079a.mp4

Wooshy is using a special API that returns only the visible elements. but it works fast because Finder return a proper list. i'll check with MailMate what it does.

**Comment by aaronrolls** [comment]
Homerow is instant. Shortcat and Vimac work, but they take about half a second to show up.

**Comment by godbout** [comment]
well. that's good news is Homerow is fast 😅️ that means i may be able to find something. will investigate, thanks.

**Comment by godbout** [comment]
i was adding MailMate to kV's Wizard so i was investigating and it works out of the box :D as far as i know it's the only one who works properly in the mail composer. all the other apps use some sort of HTML stuff which doesn't work, but MailMate is using a standard TextArea. so nice:

https://user-images.githubusercontent.com/121373/180952849-dd426705-5164-456a-9c05-b31c09fd643c.mp4

**Comment by godbout** [comment]
a3 out: https://github.com/godbout/Wooshy.docs/releases/tag/1a.3

**Comment by aaronrolls** [comment]
Takes half a second for an inbox of 200,000 messages. That is fast enough I think.

**Comment by godbout** [comment]
thank you for the heads up regarding this! definitely makes Ws way better.
