### ISSUE TITLE
Non-native App - Inkspace

### ISSUE THREAD

**Issue by hasantahir** [godbout/Wooshy.docs#23]
Reporting a few more apps where Wooshy is not working at the moment (a4):

1. [Inkspace](https://inkscape.org/)

**Comment by godbout** [comment]
hi! can you please open separate issues, one for each app. easier for me to track. thanks!

**Comment by hasantahir** [comment]
Sure, will do.

**Comment by godbout** [comment]
so, to do its magic Wooshy needs to access the UI element exposed by applications. Inkscape exposes nothing:

https://user-images.githubusercontent.com/121373/181412824-84cbb47c-6b91-4e25-9ce9-9f1e43539668.mp4

so we can't get anything, sorry.

i've posted in their forum. currently my topic is being held for review by a moderator: https://inkscape.org/forums/other/using-inkscape-with-screen-readers-on-macos/

i'm closing as there's nothing i can do. i'll update this thread when Inkscape answers or implement the macOS Accessibility. as long as you "watch" this thread, you'll receive notifications.
