### ISSUE TITLE
Way to sort out the best find

### ISSUE THREAD

**Issue by hasantahir** [godbout/Wooshy.docs#24]
<img width="898" alt="image" src="https://user-images.githubusercontent.com/11236148/181204985-66fd5ba5-b686-4166-8f2a-91fc5de9950f.png">

In the example shown in the image, Wooshy finds four `connect` instances but the meaningful one is the one which is last on the list. Can there be a way to bring to the top the ones that are associated with an interface?

**Comment by godbout** [comment]
ah. that's a good idea.

questions and blah blah below though. just in case:
1. if you don't need the menu bar, you can remove it from the search in the Preferences
2. you can reach the last item with `command down`, or `G` if you use Wooshy and kindaVim together (https://github.com/godbout/Wooshy.docs#navigate)
3. currently Wooshy follows the macOS way, that is top left to bottom right (like if you were using `tab` to go from one control to the next anywhere)

there could definitely be an option in the Preferences to allow for some kind of priority. the only thing i'm afraid about, is that it may then feel very weird to navigate through the targets. like in your case it would first navigate the interface, then go to the menu, then the status icons? i can foresee people getting lost and finding the UX quite inconsistent. what do you think?

**Comment by hasantahir** [comment]
Thanks. Just realised that if I type `connect but`, it takes me to the button where I want to be:

<img width="625" alt="image" src="https://user-images.githubusercontent.com/11236148/181306878-0212ce64-5904-4175-9cc7-7db1ed22103b.png">

The documentation shows something similar for `tab`, perhaps this should be added there as well.

I agree that coming up with some sort of order might make things messy.

**Comment by godbout** [comment]
> Thanks. Just realised that if I type `connect but`, it takes me to the button where I want to be:
> 
> <img alt="image" width="625" src="https://user-images.githubusercontent.com/11236148/181306878-0212ce64-5904-4175-9cc7-7db1ed22103b.png">
> 
> The documentation shows something similar for `tab`, perhaps this should be added there as well.

ah, yes.
it's written a bit below:
> Don't think too much, just type. e.g. tab, radio, checkbox, button, pop up, toggle. (You never need to type the whole... type, just part of it is enough most of the time.)

but it may not be clear enough. will adjust. you can type button, radio, checkbox, switch, toggle, tab, menu etc. whatever you  think, it may work.

> I agree that coming up with some sort of order might make things messy.

should we close then? :D

**Comment by godbout** [comment]
also you don't need to type the whole `connect`. probably you could type `con but`.

**Comment by hasantahir** [comment]
That's even better, thanks. That's sorted.
Cheers.
