### ISSUE TITLE
Non-native App - Zotero

### ISSUE THREAD

**Issue by hasantahir** [godbout/Wooshy.docs#25]
Wooshy a4 does not work in [Zotero](https://github.com/zotero/zotero).

**Comment by godbout** [comment]
added in a5: https://github.com/godbout/Wooshy.docs/releases/tag/1a.5

**Comment by hasantahir** [comment]
Many thanks. There are some issues (not all text readable) still, please see below:

![image](https://user-images.githubusercontent.com/11236148/181522284-ae098509-2bdc-41de-add4-e98e31c93971.png)

![image](https://user-images.githubusercontent.com/11236148/181522477-7b1d9b13-9fd2-4393-a256-5bf4a8ad9ce6.png)

**Comment by godbout** [comment]
yeah Wooshy needs the app to expose its data. Zotero seems to be a really not standard app (Java?) so i think what you're getting now is only what is accessible. the rest is not.

have you tried with other tools, like Vimac? how does it do.

i can investigate more, but i need data inside Zotero. i've tried to add stuff but i just don't get it. is there a feed or something you can give me to populate that thing? thanks.

**Comment by hasantahir** [comment]
I tried Shortcat and Homerow with the exact behaviour. Surely a Zotero problem then. I'll open an issue with Zotero if they suggest anything.

Thanks for looking into it in detail.

**Comment by godbout** [comment]
@hasantahir if you want, paste here the link to the issue you fill with them so that we can follow. you can also send them here for a discussion. thanks!

**Comment by hasantahir** [comment]
I have opened a Github issue [here](https://github.com/zotero/zotero/issues/2733#issue-1324064857) and a discussion on their forum [here](https://forums.zotero.org/discussion/98772/exposing-zotero-ui-on-macos#latest). I don't have the privilege to post on their [developer mailing list](https://groups.google.com/g/zotero-dev/search?q=UI%20).

**Comment by hasantahir** [comment]
Got a response from them and quoting it here:

> It should work as well as it works in Firefox 60 ESR. Firefox 60 didn't support VoiceOver very well, so to the extent that the apps rely on the same macOS accessibility APIs, they might not work that well with the current version.
> 
> If it works better in Firefox 102 ESR, it will work better in Zotero 7 later this year.
>

**Comment by dstillman** [comment]
Probably not that — see my [update](https://forums.zotero.org/discussion/comment/413838/#Comment_413838) and https://github.com/zotero/zotero/issues/2734.

Also, @godbout, are you only activating on certain bundle identifiers? If so, would you mind adding `org.zotero.zotero-beta`, `org.zotero.zotero-dev`, and `org.zotero.zotero-source` so this works in our dev builds and for our beta-channel users?

**Comment by godbout** [comment]
> Also, @godbout, are you only activating on certain bundle identifiers?

yes. i can't find a reliable way to avoid blasting every app with special AX attributes, and because i need to curate apps for [kindaVim](https://github.com/godbout/kindaVim.docs) that requires way more AX info, i'm using the same catalog for Wooshy. so yeah, i curate the apps. keeps Wooshy fast and not resource greedy.

> If so, would you mind adding `org.zotero.zotero-beta`, `org.zotero.zotero-dev`, and `org.zotero.zotero-source` so this works in our dev builds and for our beta-channel users?

will absolutely do. i'm not familiar with Zotero. any place where i can download the apps that hold those three bundle identifiers? for a try first. thanks.

**Comment by dstillman** [comment]
It's the exact same app, so nothing to check — we just assign different bundle identifiers to our different update channels (e.g., our [beta channel](https://www.zotero.org/support/beta_builds)).

**Comment by godbout** [comment]
> It's the exact same app, so nothing to check — we just assign different bundle identifiers to our different update channels (e.g., our [beta channel](https://www.zotero.org/support/beta_builds)).

thank you so much for taking the time and energy to answer that very dumb question 😂️ can't remember what i was thinking at the time. maybe i wanted to check the bundle identifiers myself because of a lack of trust 👀️

will add for the next alpha release (probably later today).

**Comment by godbout** [comment]
> It's the exact same app, so nothing to check — we just assign different bundle identifiers to our different update channels (e.g., our [beta channel](https://www.zotero.org/support/beta_builds)).

oh i remember now. not so dumb anymore! i need to get the bundles and try, to get the correct name to show in kV etc. thanks.

**Comment by godbout** [comment]
ok i'm seeing the beta and the official build use the same name. gonna use the same then for the beta, dev and source, at least for today's release. can be changed later.

**Comment by godbout** [comment]
@hasantahir can you try a16 and see if it works better with Zotero? https://github.com/godbout/Wooshy.docs/releases/tag/1.a16

thanks.

**Comment by hasantahir** [comment]
Thanks, @godbout for the update. Unfortunately, similar issues are being observed in Zotero. Neither the Items pane (papers list in the middle) nor the Collections Pane (list on the left) is accessible in a16.

**Comment by godbout** [comment]
@hasantahir am i dreaming or Zotero is doing much better now? if yes can we close thins? thanks.

**Comment by hasantahir** [comment]
Indeed :-) v7 has been very refreshing. 

Happy holidays!

**Comment by godbout** [comment]
> Indeed :-) v7 has been very refreshing.

looks great. didn't bother importing much info in it but overall it seems very Accessibility friendly. great news.

> Happy holidays!

THANK YOU MY DEAR FRIEND HASAN!!! happy holidays to you. and please keep sending your beautiful requests when something's not working for you with Wooshy. you've always greatly helped making Wooshy better!

**Comment by godbout** [comment]
issue on multiple monitors when second monitor has high resolution. reported on Zotero forums here: https://forums.zotero.org/discussion/122068/wrong-accessibility-data-element-position-on-macos-on-second-monitor-with-high-resolution#latest
