### ISSUE TITLE
generate a click at the current position when `return`ing on an empty Input?

### ISSUE THREAD

**Issue by godbout** [godbout/Wooshy.docs#26]
i find myself quite often clicking somewhere, then having to click again after. (not a double click.) but to click the second time, i have to retype the search term again. whoever did this is dumb! maybe pressing `return` on an empty Input could actually click at the current position?

🤔️

**Comment by godbout** [comment]
could make that an option aww 😍️ i'm smart

**Comment by aaronrolls** [comment]
Do you have an example of your issue? I think I know what you mean but I would like to be sure.

**Comment by godbout** [comment]
> Do you have an example of your issue? I think I know what you mean but I would like to be sure.

https://user-images.githubusercontent.com/121373/181417471-87dbeae0-e4ae-4d5b-b01f-0722e9c230b9.mp4

i could definitely just wait to click something else for the popover to disappear. that's just an example of what i _felt_ yesterday. but it's not the first time i have that kind of reaction while i'm using Wooshy.

**Comment by godbout** [comment]
>  ScreenFlow.mp4 

just back here to check that there's no pron in the downloads. ok safe.

**Comment by aaronrolls** [comment]
I think you idea is a good one. I can't think of anything better other than that. 

Other options could be:

- Holding the activation shortcut
- Pressing the activation shortcut twice in quick succession
- Or typing a character that isn't commonly used like `\``

**Comment by godbout** [comment]
> * Holding the activation shortcut

i'm reserving this for another use later, maybe. like you hold the activation shortcut and start typing and it highlights the targets. something in the hyperkey/superkey style.

> * Pressing the activation shortcut twice in quick succession

hmm. nice one. i like the `return` on an empty Input a bit better tho because of that feel that `return` means click somehow. also let's you open Wooshy but decide actually not to use it. should you run again the activation shortcut to "cancel" it, or press `return`? i think the `return` makes more sense for the click then. just thinking out loud here. i'm having my solution now thanks.

> * Or typing a character that isn't commonly used like ```

`i am really handsome` hahhahahahahahhahaah

**Comment by godbout** [comment]
was asking coz i was wondering whether people are/would be using `return` on an empty field to "cancel" Wooshy. well i'm gonna do the usual and add my thing as non optional first and we'll see from there. can always update later. if i don't die in the meantime. (that would be bad luck for Wooshy's users hhahhahahhhhaha.)

**Comment by aaronrolls** [comment]
> was asking coz i was wondering whether people are/would be using return on an empty field to "cancel" Wooshy.

I considered that but I haven't pressed return to "cancel" wooshy myself. I ether press the activation shortcut again or escape. I am familiar with vim so that feels natural. And considering vim users will be a large part of your target market, I don't see an issue. 

But I'll let you know if it starts to bug me in the future.

**Comment by godbout** [comment]
same here. double capslock/cancel on kV. fuck non Vim users.

**Comment by godbout** [comment]
done in a5: https://github.com/godbout/Wooshy.docs/releases/tag/1a.5

can the author close please?
