### ISSUE TITLE
Customisation options for the highlighting

### ISSUE THREAD

**Issue by roelvangils** [godbout/Wooshy.docs#27]
Under <kbd>👄 Looks</kbd> in Settings, there are options for customising the Input field and the targets. Do you plan to add customisation options for the screen highlights as well (is that what you call them?).

If so, I have a few suggestions!

You could add an option to follow the system highlight colour:

![20220727_144807_System Preferences@2x](https://user-images.githubusercontent.com/103744/181250614-a87d6291-5b6b-402a-ad7e-4d75db23e0d3.png)

But what I would like _even more_ (as a low vision user) is the option to add a (high contrast) accessible highlight indicator that is styled the same way as the one that VoiceOver provides.

The VoiceOver virtual focus indicator one works perfectly well on all background colours because it's a triple outline: 4px black as the main border and 2px white as the inset and outset border (on Retina resolutions, otherwise it's 1+2+1). You could make it exactly the same for low vision users.

Example:

<img width="274" alt="20220727_145220_Sketch@2x" src="https://user-images.githubusercontent.com/103744/181251335-15c43054-2554-4027-b2bf-a4ebbf4ffec4.png">

The reason why this is so important to me is that I am [completely colourblind](https://en.wikipedia.org/wiki/Achromatopsia). There is no colour that works well for me on all backgrounds, so the white+black+white focus VO-style indicator is ideal for me.

Thanks for considering! :)

**Comment by godbout** [comment]
> Under 👄 

HAHHHAHAHA I LOVE IT

> Under 👄 Looks in Settings, there are options for customising the Input field and the targets. Do you plan to add customisation options for the screen highlights as well (is that what you call them?).

yes! actually what i call `Targets` are the yellow highlights (the primary one being creatively called the Primary Target): https://github.com/godbout/Wooshy.docs#v1

my plan was to work on that after v1 is released. i thought about doing something similar to The Input. a bunch of slider to change the color, border, radius, etc. 

> You could add an option to follow the system highlight colour:
> 
> ![20220727_144807_System Preferences@2x](https://user-images.githubusercontent.com/103744/181250614-a87d6291-5b6b-402a-ad7e-4d75db23e0d3.png)

actually at first i thought this is what i was doing. i'm not using yellow. i'm using the color of the `find highlight` under macOS. i thought this was changing with the accent color, but it doesn't. sad. ☹️
the issue with the accent color though is: i don't know if they would all be readable. i have to investigate.

> But what I would like _even more_ (as a low vision user) is the option to add a (high contrast) accessible highlight indicator that is styled the same way as the one that VoiceOver provides.
> 
> The VoiceOver virtual focus indicator one works perfectly well on all background colours because it's a triple outline: 4px black as the main border and 2px white as the inset and outset border (on Retina resolutions, otherwise it's 1+2+1). You could make it exactly the same for low vision users.
> 
> Example:
> 
> <img alt="20220727_145220_Sketch@2x" width="274" src="https://user-images.githubusercontent.com/103744/181251335-15c43054-2554-4027-b2bf-a4ebbf4ffec4.png">
> 
> The reason why this is so important to me is that I am [completely colourblind](https://en.wikipedia.org/wiki/Achromatopsia). There is no colour that works well for me on all backgrounds, so the white+black+white focus VO-style indicator is ideal for me.
> 
> Thanks for considering! :)

that is very sensible. love this.

**Comment by roelvangils** [comment]
![Awesome!](https://user-images.githubusercontent.com/103744/181294927-632c821c-b7f2-4cd1-8a3a-1334fbcf6356.gif)

**Comment by godbout** [comment]
i understand the excitement but please no violence here. (and also no jokes.)

**Comment by roelvangils** [comment]
Indeed, that is the beauty of it! The accessible outline is always the same and doesn't need to change depending on the background. To see how it looks in action, just activate VoiceOver!

**Comment by godbout** [comment]
![boom-mind-blown](https://user-images.githubusercontent.com/121373/181403593-e63fe2dd-fdda-49f8-bf2f-7cf249e58ac4.gif)

well i'm on some other stuff but again, top of the list. THANK YOU!

**Comment by godbout** [comment]
@roelvangils i'm trying to get VoiceOver to show me that highlighting you're having and i don't get it sorry. could you walk me through getting this to work so that i can how it looks? thanks.

**Comment by godbout** [comment]
ok, got it. but it's been tough. i activated the curtains and my screen was full black even after reboot and i had to navigate menus not seeing anything. what a ride.

**Comment by roelvangils** [comment]
LOL! 🤣 Don't enable Screen Curtain. It's torture. Next time if your screen is black, use three fingers to triple-tap your trackpad (or use the [keyboard shortcut](https://support.apple.com/en-us/HT201443) described here).

Did you see what that focus highlight looks like? Did you like it? :) It's not the prettiest, but it's a cool accessibility feature.

**Comment by godbout** [comment]
> LOL! 🤣 Don't enable Screen Curtain. It's torture. Next time if your screen is black, use three fingers to triple-tap your trackpad (or use the [keyboard shortcut](https://support.apple.com/en-us/HT201443) described here).

actually found that article on my phone yes, but it wouldn't work. not sure if it's because i enabled the option to move window with 3 fingers move on the trackpad.

so i had to find how to open the menu without seeing anything, then go down to Visual, then enable curtains again 😂️ works pretty well actually.

> Did you see what that focus highlight looks like? Did you like it? :) It's not the prettiest, but it's a cool accessibility feature.

yes.
i think today i'm taking it easy and i'm just gonna release a fun version where you can choose your own colors. but not the VoiceOver style yet. i'm playing with it but it's more complicated than the rest. i need more time to think how i can do it better.

**Comment by godbout** [comment]
this is what i have for now:

https://user-images.githubusercontent.com/121373/182558431-959d8da0-193c-4751-aafd-acd3bba9df86.mp4

too thick. and primary target is black. the logic is gonna have to be different from the current implementation that works with all the colors. so yeah, need some more invesgitation.

**Comment by godbout** [comment]
hopefully i'm not gonna trigger your OCD too much by releasing almost daily... 😬️😂️

**Comment by roelvangils** [comment]
No, I like it :) Every update is a little 🎁. And it already looks quite good, in the screencast!

**Comment by godbout** [comment]
well it's always easy to make it "look" good 😄️
it takes quite a while to get the structure and the engines in place, but once they are the changes can be done quite fast and solid. but i hadn't planned for several borders for the Targets, so i need to make it in a way that it's sustainable and maintainable. what you see in the screencast is just a gross hack. that being said, it shouldn't take long. probably a couple of days max.

then... i think you can guess the name of that release... ❤️

**Comment by roelvangils** [comment]
I feel all warm and fuzzy inside now!

**Comment by godbout** [comment]
have you tried alpha 9 and the different colors? if yes, any hanging? it's working well here (Monterey and Ventura) but there's an issue reporting that it hands: #46

**Comment by godbout** [comment]
so @roelvangils as you saw there's a first draft of the VoiceOver thing. now as expected, it's a bit more tricky than it seems. because of the triple borders, it takes space. i can't take too much space, because then menus and other UI elements start overlapping each other. but as you'll see, sometimes you end not really being able to read the text if the height is too small.

so what i'd recommend is try it for a few days and see how it feels. then come back with your feedback, and we'll fine-tune accordingly. thanks for the idea, that was a great one. i wouldn't have think of it myself for sure.

**Comment by godbout** [comment]
VoiceOver improved in a15: https://github.com/godbout/Wooshy.docs/releases/tag/1.a15

can you let me know if there's enough breathing room now? if i add more padding, the Targets start eating each other. another way would be to reduce the border widths, but it looks less nice i think. up to you. let me know.

**Comment by godbout** [comment]
please reopen if the VoiceOver preset is not good enough. thanks.

**Comment by godbout** [comment]
@roelvangils still using the VoiceOver preset? i'm trying to update it for the round corners in macOS 26. mega pain 😂 almost thought about getting rid of it (just a feel. not gonna do it.) but curious if you're still using it. i would guess so.

**Comment by roelvangils** [comment]
To be honest, no! 🙈 I siwtched to this setting a while ago (still using Wooshy, of course). The VoiceOver style was a bit too much and I figured out that this color scheme was quite readable for me, too. You don't have to keep it around just for me :) 

<img width="452" height="644" alt="Image" src="https://github.com/user-attachments/assets/115d8c36-7730-4138-a579-3fdda7b067c5" />

**Comment by godbout** [comment]
i'm adding options to tweak the borders width and radius so that the Targets feel more at home on macOS 26:

https://github.com/user-attachments/assets/c926cff4-30c1-4326-94ae-aecbf902d63d

and it's A LOT of calculations even for the simple borders. the VoiceOver is a lot of borders and insets and it's a fucking nightmare and i'm really thinking about getting rid of it now yeah 😂😂😂

edit: hope you can still handle the Fuchsia :D
