### ISSUE TITLE
Not working on Notion Desktop/Notion Enhanced

### ISSUE THREAD

**Issue by archetyped** [godbout/Wooshy.docs#28]
Notion Desktop is essentially a desktop wrapper for the website, but Wooshy _does_ work with the Notion website in standard web browsers.

## Downloads

* Official: https://www.notion.so/desktop
* Enhanced: https://github.com/notion-enhancer/desktop

**Comment by godbout** [comment]
are you on alpha 4? i've added Notion a couple of alphas ago.
not the Enhanced one tho. will add.

**Comment by godbout** [comment]
Uploading ScreenFlow.mp4…

**Comment by godbout** [comment]
> Uploading ScreenFlow.mp4…

LOL

https://user-images.githubusercontent.com/121373/181404856-874cee09-1f32-40d6-9b01-54a0a8e7509d.mp4

**Comment by godbout** [comment]
ok i misunderstood the Enhanced stuff. i thought it was like a beta or something, like Discord with their multiple apps.

can you let me know if it works for you with alpha 4 before i start investigating the Notion plugin? thanks.

**Comment by archetyped** [comment]
Yes, alpha 4

**Comment by godbout** [comment]
added in a5: https://github.com/godbout/Wooshy.docs/releases/tag/1a.5
