### ISSUE TITLE
Feature Request: Move the mouse without clicking

### ISSUE THREAD

**Issue by aaronrolls** [godbout/Wooshy.docs#29]
It is something I use infrequently with Homerow, but I still use it and it would be nice to have the same feature in Wooshy.

**Comment by godbout** [comment]
yeah i have this in my internal list but like really low. i've never used it myself. care to share how/why you use this functionality?

also, what keyboard shortcut would be nice? i'm not gonna allow config, at least not at the beginning.

**Comment by godbout** [comment]
also i'm hiring you. can you have a look at this: https://github.com/godbout/Wooshy.docs/issues/26 and give me your thoughts? thanks!

**Comment by aaronrolls** [comment]
One instance is if you are watching a video. Clicking would pause the video but a mouse over would bring up the UI without interfering with playback. 

The menu open buttons on some websites will take you to a url if you click on them, you can only see the actual menu if you hover your mouse over the button. Can't think of any examples right now though.

>  also i'm hiring you. can you have a look at this: https://github.com/godbout/Wooshy.docs/issues/26 and give me your thoughts? thanks!

Great. I'll take a look.

**Comment by godbout** [comment]
> One instance is if you are watching a video. Clicking would pause the video but a mouse over would bring up the UI without interfering with playback.
> 
> The menu open buttons on some websites will take you to a url if you click on them, you can only see the actual menu if you hover your mouse over the button. Can't think of any examples right now though.

well i'm sold.

also

> also, what keyboard shortcut would be nice? i'm not gonna allow config, at least not at the beginning.

might make it for today's (nightly build) release :D

**Comment by aaronrolls** [comment]
> also, what keyboard shortcut would be nice? i'm not gonna allow config, at least not at the beginning.

If possible I would like cmd+shift+return. Resonates with shifting the mouse.

**Comment by godbout** [comment]
sounds good. you got it.

**Comment by godbout** [comment]
done in a5: https://github.com/godbout/Wooshy.docs/releases/tag/1a.5

**Comment by godbout** [comment]
hey just to let you know. if you press `shift command return` while The Input™ is empty, then you move the mouse to its current location. the best feature of Wooshy by far.
