### ISSUE TITLE
Wooshy can't click some text links that exist on two lines at the same time

### ISSUE THREAD

**Issue by aaronrolls** [godbout/Wooshy.docs#30]
If the link is on ether line, Wooshy handles it correctly, but if the link is on two different lines a the same time [like this extra long link](https://www.youtube.com/watch?v=dQw4w9WgXcQ) Wooshy will highlight the group of text and click the middle of the highlight, not the link.

If the link is not present on two lines, resize the browser window until it is.

**Comment by aaronrolls** [comment]
Homerow solves this by clicking the bottom left of the highlighted box, just like the accessibility inspector does on a press action. 

Since I can't see any info in the accessibility inspector that would let Wooshy know that the link is spanning two lines the only way I can think of is getting the text size and checking if it is double (or more than single). Or just clicking the bottom left of every link like homerow does.

**Comment by godbout** [comment]
> If the link is on ether line, Wooshy handles it correctly, but if the link is on two different lines a the same time [like this extra long link](https://www.youtube.com/watch?v=dQw4w9WgXcQ) Wooshy will highlight the group of text and click the middle of the highlight, not the link.

wow that demo is really something. thank you. i don't think in the life of Wooshy and kV anyone ever took the time to show something so precisely. i believe lots of people need to see this.

**Comment by godbout** [comment]
> i believe lots of people need to see this.

done. https://twitter.com/wooshyapp/status/1552570404425723904
you gonna be famous.

**Comment by aaronrolls** [comment]
> wow that demo is really something. thank you. 

Thanks I put a lot of work into that one.

**Comment by godbout** [comment]
> If the link is on ether line, Wooshy handles it correctly, but if the link is on two different lines a the same time [like this extra long link](https://www.youtube.com/watch?v=dQw4w9WgXcQ) Wooshy will highlight the group of text and click the middle of the highlight, not the link.
> 
> If the link is not present on two lines, resize the browser window until it is.

i wasn't aware of this issue. i have another one where sometimes it clicks in between the links somehow (like in Alfred Notification forum post thing) but it rarely happens so it wasn't high priority. webpages are always a mess. many times the "link" you see is is not the link there is. like those:

![Screenshot 2022-07-28 at 16 27 18](https://user-images.githubusercontent.com/121373/181459079-bcae5698-d103-4b80-8074-02f238e02402.png)

this even goes out of the main app window. of course you have sites with the same thing happening but on the other side. like you can't easily know if you should click left or right or top or bottom. those custom UI shits are so painful. same with Electron shits.

but yeah, needs to be looked at. the Inspector press action is a great idea. can't believe i didn't have it first ☹️

**Comment by godbout** [comment]
> Thanks I put a lot of work into that one.

that definitely deserves more sponsoring: https://twitter.com/godbout/status/1552581438280589312

**Comment by godbout** [comment]
this seems much better. the few places where i had issues are gone. and there's no new place where it fails. also it clicks close to the edges so it's been a little frightening at first 😂️

**Comment by godbout** [comment]
Rick Astley now reachable in a8: https://github.com/godbout/Wooshy.docs/releases/tag/1a.8

**Comment by aaronrolls** [comment]
Great, thank you. Love that face...
