### ISSUE TITLE
not working on Asana

### ISSUE THREAD

**Issue by roelvangils** [godbout/Wooshy.docs#32]
![fox-tv-crying-gif-by-screamqueens](https://user-images.githubusercontent.com/103744/181474131-cc5b9f28-7238-475a-b66e-5448e7a04ab4.gif)

**Comment by godbout** [comment]
1. life is not fair
2. YOU ARE TOO SLOW!!! my Brazilian friend got there first: https://github.com/godbout/Wooshy.docs/issues/6
3. 😗️
