### ISSUE TITLE
Key combo

### ISSUE THREAD

**Issue by roelvangils** [godbout/Wooshy.docs#33]
While experimenting with what **the ideal** shortcut (for me) would be for triggering Wooshy, I landed on <kbd> ⌃ Control</kbd> + <kbd>⏎ Enter</kbd>. It's nice because it requires minimal effort, it's all done with the right hand, and you can immediately start typing with your left hand (and quickly add your right one too). In most cases, you can keep your right index or middle finger hovering over the Enter key to confirm your action. It's very quick. I forgot what the default shortcut was in Settings.

![20220728_141056_Sketch@2x](https://user-images.githubusercontent.com/103744/181501801-cc1e5951-8dd2-486f-b1c3-dbaa10548e0c.png)

**Comment by godbout** [comment]
i can't make my mind whether this issue is a troll or not 🤔️

**Comment by godbout** [comment]
1. first, what kind of keyboard is that LMAO where are the fucking arrow keys???
2. ok if this is not a troll: you can access the Settings from the menu bar, and you can set your own custom keyboard shortcut, `control return` included:

https://user-images.githubusercontent.com/121373/181570139-999227db-20bb-4d6d-bfa7-4b213f51a07f.mp4

in case this is a troll well done you got me 😂️

**Comment by roelvangils** [comment]
Of course, that is why I did :) I was just "announcing" that I like my shortcut much better than your default one! ;)

**Comment by roelvangils** [comment]
And the image is a cropped version of this one :)

<img width="598" alt="20220728_170147_Safari@2x" src="https://user-images.githubusercontent.com/103744/181571196-f0d3e219-4ed3-42aa-8485-5cb1903296ff.png">

**Comment by godbout** [comment]
oh ok, i see. so this is more like something you're sharing? or do you have any expectation, like for `control enter` to become the shortcut coming with Wooshy?

also, really, the keyboard. AFAIK Apple keyboard don't even have a `control` key on the right. is that a Belgium thing?

**Comment by godbout** [comment]
> And the image is a cropped version of this one :)
> 
> <img alt="20220728_170147_Safari@2x" width="598" src="https://user-images.githubusercontent.com/103744/181571196-f0d3e219-4ed3-42aa-8485-5cb1903296ff.png">

ohhhh i see. ok. but my guess is that most people don't use the wide keyboard. they're on a laptop one, or a small Magic one, like those:

https://www.apple.com/shop/product/MK2A3LL/A/magic-keyboard-us-english

no `control` on the right.

anyways, this is customizable, and i'm sending users to the Settings, on that page with the custom shortcut right after the approved the AX permissions. so i think that'll be the best for now.

**Comment by roelvangils** [comment]
It's great that it's customisable as everyone has different preferences (and there are different keyboard layouts). I like the full-size keyboard! And for this shortcut, I want it to be as _frictionless_ as possible because (I imagine) if you're getting used to this app, you'll start using it all the time. That is why I ultimately decided that right ctrl+enter was right for me :)

**Comment by godbout** [comment]
well Sir i have to say, i am very happy that you have found the right key combo for yourself, and that Wooshy is customizable, and that this key combo is available. now you'll get so used to it that you may use it while you sleep.

**Comment by godbout** [comment]
if there's nothing to do i'm gonna close. trying to keep the list clean. lots of things to do :D

please reopen if i've missed something.
