### ISSUE TITLE
not working on Telegram

### ISSUE THREAD

**Issue by jannis-baum** [godbout/Wooshy.docs#35]
[from the App Store](https://apps.apple.com/us/app/telegram/id747648890)

**Comment by godbout** [comment]
good point. there was already a thread but i closed it coz the investigation is currently over, and we're not waiting for the Telegram's devs to implement the AX on their side.

**Comment by godbout** [comment]
i've reopened the other one (https://github.com/godbout/Wooshy.docs/issues/1), will close this one, and add tags.
