### ISSUE TITLE
Not finding email list with Apple Mail

### ISSUE THREAD

**Issue by aaronrolls** [godbout/Wooshy.docs#4]
When using Apple Mail, Wooshy will not find anything in my email list when I have "All Inboxes".

![CleanShot2022-07-25at21 35 04](https://user-images.githubusercontent.com/47949221/180746925-c6263d00-30f9-42e8-ba32-8f2c93e522cd.png)

Wooshy thinks for a couple of seconds then ignores the email list.

However when I try using Wooshy in an individual mailbox with only 23,000 emails it does work as expected, although it takes a couple of seconds to be ready.

I would think, that like Mailmate, Wooshy is trying to process accessibility info for every email rather than just the emails on screen.

For context, Homerow is instant, but Wooshy does give better options.

**Comment by godbout** [comment]
> For context, Homerow is instant

interesting. i have it the other way around. Homerow going through list of non visible stuff while Wooshy doesn't 🤔️

> but Wooshy does give better options.

that might be the key. what's the difference? can you still click single emails with Homerow?

**Comment by aaronrolls** [comment]
I can click single emails with homerow but I will only get one option for each email with homerow. With Wooshy I will get an option for the sender, title and body.

Wooshy is way faster on an inbox of only 2000, almost instant, than it is on an inbox of 20,000.

**Comment by godbout** [comment]
yeah i can reproduce and see a difference here. although it doesn't seem to be (only) about the number of emails, but also the number of reachable targets by emails (i have big boxes where it goes fast, smaller boxes where it's slower). will investigate. thanks.

**Comment by godbout** [comment]
ok so i've investigated and yes, i should get back the visible children from the mail list but instead i'm receiving all the children from the AX APIs. so in my case it's looping over 25k items (and discard them as they're out of the window frame). so basically Wooshy is raping your computer sorry hahaha.

**Comment by godbout** [comment]
do you mind trying an alpha of the next alpha? 😅️
faster here, but would be nice to know with your setup. and compared to the other tools you use.

**Comment by aaronrolls** [comment]
> so basically Wooshy is raping your computer sorry hahaha.
No worries, all part of the process. 

> do you mind trying an alpha of the next alpha? 😅️

Yeah sure, that would be great. My email if you need it is public@aaronrolls.nz

**Comment by godbout** [comment]
actually will release a3 publicly today.

you gonna love it.

https://user-images.githubusercontent.com/121373/180905666-4e8b4d8b-7f58-427b-8001-cab171bba510.mp4

**Comment by aaronrolls** [comment]
I believe I am. Looks great.

**Comment by godbout** [comment]
a3 out: https://github.com/godbout/Wooshy.docs/releases/tag/1a.3

**Comment by aaronrolls** [comment]
I can confirm that it is very fast now. Apple mail is instant. Mailmate takes about half a second for the 200,000 messages. Nice work.

**Comment by godbout** [comment]
now the total number of emails shouldn't matter anymore. what should matter is 1) the rows visible on the screen 2) how much data each row has. i'm pulling more data than HR/SC, so might be slower. how does it compare with those? @aaronrolls

**Comment by aaronrolls** [comment]
It is slower, but you have to be looking for it to notice. Fraction of a second. I have an M1 Macbook Pro, so it might be slower on older machines.
