### ISSUE TITLE
sometimes clicks are not registered

### ISSUE THREAD

**Issue by godbout** [godbout/Wooshy.docs#41]
https://user-images.githubusercontent.com/121373/182008537-b54bf47c-a186-43ea-94e3-abba588c3a34.mp4

**Comment by roelvangils** [comment]
So it's not just me :)

**Comment by godbout** [comment]
🙌️

any other place where you've experienced this?

**Comment by roelvangils** [comment]
> any other place where you've experienced this?

I'll keep an eye on it and add it here as a comment.

**Comment by godbout** [comment]
fixed in a8: https://github.com/godbout/Wooshy.docs/releases/tag/1a.8
