### ISSUE TITLE
not working on Vimcal

### ISSUE THREAD

**Issue by dudunato** [godbout/Wooshy.docs#44]
🫢

**Comment by godbout** [comment]
wait this is a site, not an macOS app?

seems the whole thing is not accessible. will ping the devs.

**Comment by godbout** [comment]
oh ok, found the app. was hidden. also not easily downloadable. keep closing the window. what are you doing this to me my dudu.

**Comment by godbout** [comment]
added in a8: https://github.com/godbout/Wooshy.docs/releases/tag/1a.8
