### ISSUE TITLE
Inception

### ISSUE THREAD

**Issue by roelvangils** [godbout/Wooshy.docs#45]
![20220803_125229_Slack@2x](https://user-images.githubusercontent.com/103744/182591347-379af4a9-b902-410b-8306-b4c6e1f025e7.png)

**Comment by roelvangils** [comment]
![inception-gif](https://user-images.githubusercontent.com/103744/182591474-a702ce9c-fa3d-4672-bbaf-44d8422f390a.gif)

**Comment by godbout** [comment]
not working? i've been deliberately make it work on itself. should work fine. what issues you have?

**Comment by roelvangils** [comment]
Haha, no of course it works :) It's just funny that you didn't exclude your on app.

**Comment by godbout** [comment]
ah. coz that part of course is not curated. it's just to guide users, if they have a problem. if they don't, no need to care. also, no special treatment for my own apps hahhahhahahhh.
