### ISSUE TITLE
Search box reset to bottom-left corner when Position set to "where you left it" on launch

### ISSUE THREAD

**Issue by archetyped** [godbout/Wooshy.docs#49]
When Wooshy is quit and relaunched, the search box is positioned in the bottom-left corner of the screen if the Position setting is set to "where you left it".

This occurs regardless of where the search box was positioned before Wooshy was quit and relaunched.

* Wooshy version: at least 1a8-1a10

**Comment by godbout** [comment]
good point. this is handled by macOS itself. but not ideal yeah. will check what i can do, thanks for reporting.

**Comment by godbout** [comment]
fixed in Ws30: https://github.com/godbout/Wooshy.docs/releases/tag/30
