### ISSUE TITLE
not working on Rambox

### ISSUE THREAD

**Issue by johnallen3d** [godbout/Wooshy.docs#52]
I use Rambox as a wrapper around multiple GMail accounts. While GMail has excellent keyboard shortcuts elements within an email are unreachable via keyboard. It would be great if Wooshy could help with this! 😁

**Comment by godbout** [comment]
coming later today in a13, but:

https://user-images.githubusercontent.com/121373/183409275-157cf7d9-f65e-43fb-b52e-c94cbb7e8fbc.mp4

they're missing a lot of Accessibility information. they haven't put anything there. so for many buttons, the only way to get there with Wooshy is to filter by `button`, and navigate. not cool. i'll ping them and ask them if they can add accessibility info. not sure why a lot of apps don't do it, it's super easy, and very needed for low vision/blind people who rely on VoiceOver (and needed for me to amass billions of dollars).

**Comment by johnallen3d** [comment]
Thank you!!!

I have a son with special needs and it warms my heart to think that your efforts on Wooshy might help make computer usage in the future more accessible. 🥰

**Comment by godbout** [comment]
btw you'll need to try Rambox and see for yourself if it "works" or not. Wooshy will work in the sense that it'll grab all the stuff available. but you may not be able to reach Targets easily because of what i've mentioned above, the lack of AX info from their side.

**Comment by godbout** [comment]
@johnallen3d as a user of Rambox, you could create a ticket on their support system: https://support.rambox.app/support/home
the more people ask the better.

**Comment by godbout** [comment]
added in a13: https://github.com/godbout/Wooshy.docs/releases/tag/1.a13

created two support ticket:
1. for undo/redo not working in Rambox it seems, for text input
2. for the AX info missing

i'd recommend doing the same. closing here for now. i'll add comments once the Rambox people update me on those issues.

**Comment by johnallen3d** [comment]
I'll create a ticket as well, thanks again!

**Comment by godbout** [comment]
yep, no worries.

let me know later after you use a13 with Rambox if it's fine or it's missing stuff. it happens that Electron are funky in how they design their UI and sometimes my engines need to be tweaked. as long as the tweaks make Wooshy better overall, i'll do them. thanks!

**Comment by johnallen3d** [comment]
To be honest I'm mostly interested in selecting elements within emails (e.g. links/buttons). With a13 that is working beautifully! 🥇

**Comment by godbout** [comment]
😎️ enjoy the rest of the week then. also the week after.

**Comment by godbout** [comment]
my GitHub profile has a sponsor button. also most of my open source project i think. only kV and Wooshy don't because they're paid apps. but don't bother. the GitHub sponsoring goes to my French account, so it all goes to taxes.

if you really wanna help there's a few ways:
1. you can subscribe to Wooshy when the v1 is out (if it still bring value to you of course. actually the Early Support has already started. there's already 6 mice that got their freedom back)
2. you can share your enthusiasm about it with some people that you think may be interested
3. you can wire a million dollars to my bank account (but not the French one)

**Comment by johnallen3d** [comment]
1. Will plan on subscribing to Wooshy when that's an option. ✅
2. I've already messaged several of my keyboard nerd friends. ✅
3. 🤔

**Comment by godbout** [comment]
![Screenshot 2022-08-08 at 23 32 25](https://user-images.githubusercontent.com/121373/183455823-3120e74c-716b-4d11-8719-e5fbaa078568.png)

https://subscribe.wooshy.app

:p

but you don't have to really. just keep enjoying it the way it is. just answering coz it's my answering time. (and also i'm anal about not letting things dangling.)

ok, i'm out now!
