### ISSUE TITLE
Add support for shortcuts

### ISSUE THREAD

**Issue by roelvangils** [godbout/Wooshy.docs#56]
Bit ironic maybe (sorry) but I think it would be good if the app would also support these "best practice shortcuts" for macOS settings. I know not all apps support these, but I think Wooshy users will be appreciate these shortcuts to work, before resorting to the Wooshy-way of clicking one of the options 🙂 
 
![20220809_221732_Wooshy@2x](https://user-images.githubusercontent.com/103744/183752878-39ce0f07-114c-47a5-9cb6-49721496862f.png)

**Comment by godbout** [comment]
> I think it would be good if the app would also support these "best practice shortcuts"

definitely agree.

> "best practice shortcuts" for macOS settings.

i have never seen this anywhere. there's no documentation in Apple's HIG about this, and as far as my tests go, it doesn't work in any macOS standard native app. where have you seen this?

**Comment by godbout** [comment]
> i have never seen this anywhere. there's no documentation in Apple's HIG about this, and as far as my tests go, it doesn't work in any macOS standard native app. where have you seen this?

**Comment by roelvangils** [comment]
You're right. It's not a best practice at all, but some apps have it. Raycast, for example. I just wish it was more common :)

**Comment by godbout** [comment]
yes, Raycast is completely custom, they don't follow the macOS standard in the Settings. the Settings, in the case of Wooshy and kV, is handled by macOS. could have a look if i can add keyboard shortcuts tho.

**Comment by godbout** [comment]
although that is quite super cool to use Wooshy on the tabs to go through Wooshy's Settings itself, imho.

**Comment by godbout** [comment]
closing. will reopen or do if/when this becomes a macOS standard.
