### ISSUE TITLE
not working on Telegram, the Electron version

### ISSUE THREAD

**Issue by godbout** [godbout/Wooshy.docs#60]
same as #1. no AX info available even after blasting the app with the necessary Electron shit attributes. pinged the dev, but still no answer.

**Comment by pugson** [comment]
you won't ever get a response from them unfortunately. https://blog.borodutch.com/i-quit-telegram-heres-why/

**Comment by godbout** [comment]
what a pity. honestly i don't even get what they're doing with the last updates. kindaVim was working out of the box beautifully because they were handling the macOS AX perfectly. for Wooshy it was a bit more tricky but you were still able to grab conversations. now you can't do shit at all. they broke the whole stuff. really strange. hopefully it's as a result of something else that is needed in Telegram? wouldn't believe if they just broke stuff without any good reason.

**Comment by godbout** [comment]
closing coz nothing we can do except crying.
