### ISSUE TITLE
not working on Arc

### ISSUE THREAD

**Issue by clouedoc** [godbout/Wooshy.docs#62]
I would like to use this shiny new browser with Wooshy.
It's a Chromium-based browser.

It's still in limited-beta, so you won't be able to get your hands on a binary right now (unless I give you my keys, which I totally could if you're that invested in the happiness of your users 🤷)
Here's a link to it if you're interested: https://thebrowser.company/

It worked well with Wooshy, but stopped yesterday after they auto-updated it 😢 .
It cannot find elements on any webpages.

Where should I start to investigate?

**Video demo**
https://user-images.githubusercontent.com/13921610/185936782-4f25439b-30e8-4a5c-b51b-ede3acfb3532.mov

(it works well with Safari and Chrome)

**Comment by clouedoc** [comment]
(shortcat works though 🤔)

![image](https://user-images.githubusercontent.com/13921610/185938633-77e613cf-c515-4d63-bac1-ebafaff980a6.png)

**Comment by godbout** [comment]
first, 🙏️❤️

**Comment by godbout** [comment]
second, yes, people have been sending me invites but they seem to manually approve them and they're super picky. so i'm gonna attach an app in the next comment. run the app, drop `Arc` on it. it will copy the `Bundle Identifier` in your clipboard. paste it here, and i'll take care of the rest.

**Comment by godbout** [comment]
[BundleIdentifier.app.zip](https://github.com/godbout/Wooshy.docs/files/9394973/BundleIdentifier.app.zip)

**Comment by godbout** [comment]
> BundleIdentifier.app.zip

you may need to approve it from the `Security & Privacy` shit. not sure if it's code-signed.

**Comment by godbout** [comment]
> (shortcat works though 🤔)
> 
> ![image](https://user-images.githubusercontent.com/13921610/185938633-77e613cf-c515-4d63-bac1-ebafaff980a6.png)

yes. so, Shortcat is blasting every app with some special AX attributes. i don't do this. this is breaking windows manager, and some standard keyboard shortcuts in some apps (for example, try using Shortcat on Safari, you'll see that you can't go up/down a page anymore with the `up/down` arrows).

the way i do is different. because i need to curate apps anyways for [kindaVim](https://github.com/godbout/kindaVim.docs), i target specifically. like for example, if i had access to `Arc`, i would test it with kV, i would add to The Wizard, and it would be added to Wooshy also 😎️

so it takes a bit more time to "curate" the apps, but at least your system is clean.

**Comment by godbout** [comment]
i may do a release in a few hours. if i get the `Bundle Identifier` then i can add `Arc` in a18.

**Comment by clouedoc** [comment]
> 

![image](https://user-images.githubusercontent.com/13921610/185940058-16798be2-d5f8-4206-b798-5fb1b6929f30.png)

It requires MacOS 13. Would you mind building a version for MacOS 12?

**Comment by clouedoc** [comment]
> second, yes, people have been sending me invites but they seem to manually approve them and they're super picky. so i'm gonna attach an app in the next comment. run the app, drop `Arc` on it. it will copy the `Bundle Identifier` in your clipboard. paste it here, and i'll take care of the rest.

It's weird that they would approve me but not you, especially since you've been invited so much 🤔 
Maybe they want to hide their failing accessibility support 😄

**Comment by godbout** [comment]
> ![image](https://user-images.githubusercontent.com/13921610/185940058-16798be2-d5f8-4206-b798-5fb1b6929f30.png)
> 
> It requires MacOS 13. Would you mind building a version for MacOS 12?
> 
> (forcing it to run doesn't work, unsurprisingly lol)
> 
> ![Capture d’écran 2022-08-22 à 16 06 26](https://user-images.githubusercontent.com/13921610/185940980-b9922306-093b-4b72-9bc7-324fb7594a55.png)
> 
> ![Capture d’écran 2022-08-22 à 16 06 10](https://user-images.githubusercontent.com/13921610/185940926-bc8f5d9f-4a65-417b-9636-88d980ffeeb9.png)

ah yes. always at the edge 😎️
shitting a macOS 12 version now.

**Comment by godbout** [comment]
> (forcing it to run doesn't work, unsurprisingly lol)

probably the French language.

**Comment by clouedoc** [comment]
Probably. Computers don't like us

**Comment by clouedoc** [comment]
![image](https://user-images.githubusercontent.com/13921610/185943065-5de88835-ae4c-4769-82ba-08d1b6662778.png)

Are you linking for this small string?

**Comment by godbout** [comment]
[BundleIdentifier.app.zip](https://github.com/godbout/Wooshy.docs/files/9395105/BundleIdentifier.app.zip)

**Comment by godbout** [comment]
> ![image](https://user-images.githubusercontent.com/13921610/185943065-5de88835-ae4c-4769-82ba-08d1b6662778.png)
> 
> Are you linking for this small string?

well that's it 😂️

**Comment by godbout** [comment]
> Probably. Computers don't like us

![completly-normal-phenomenon-chernobyl](https://user-images.githubusercontent.com/121373/185943344-ea6e70f0-104b-4eab-9cb4-29b6f3c0face.gif)

**Comment by clouedoc** [comment]
Lol ok, awesome because your small app is still not tolerating my clunky old system 😂 
![image](https://user-images.githubusercontent.com/13921610/185943438-6a5fcb7d-8d60-4ea6-bf46-1d57902644a4.png)

**Comment by godbout** [comment]
> Lol ok, awesome because your small app is still not tolerating my clunky old system 😂
> ![image](https://user-images.githubusercontent.com/13921610/185943438-6a5fcb7d-8d60-4ea6-bf46-1d57902644a4.png)

even the new one? probably i fucked up. anyways yeah i needed that string. so it's perfect. coming later today.

**Comment by clouedoc** [comment]
Yeah I think you messed up, I've tried to extract the new ZIP 5 times 🤔 
Excited to take my mouse on hollidays again 🙏

**Comment by godbout** [comment]
yeah there's actually two places to change this, in the project and in the target. i missed one. n00b.

**Comment by godbout** [comment]
how is Arc doing with kV? if they use the same Chromium-base, there may be a bug currently in their AX (notified. fixed. now waiting for release on their side.) and kV would fail on multilines. so i guess it should go to PG-R (if not failing), else to Key Mapping (if failing). can you let me know? so that i add this at least temporarily in The Wizard. merci !

**Comment by godbout** [comment]
> Indeed, Arc+kindaVim doesn't work right off the bat. Text deletion does not work by default, so I had to put it in PG-R mode.
> 
> Still with this mode, going to the line below with "j" has a weird behavior (J works fine on the start of a line; in the middle of a sentence, it makes the cursor go to the right, though)

ok so i can't test so i can't be sure exactly but this may be the same issue as Chrome/Brave: https://github.com/godbout/kindaVim.docs/issues/72

from the Chromium dev team: https://bugs.chromium.org/p/chromium/issues/detail?id=1325643
i also have private emails with them.

it's fixed but not released yet publicly. need to wait a bit... so for the time being, it needs to go to Key Mapping.

**Comment by godbout** [comment]
(also, that typing skill aww 😍️😍️😍️😍️😍️😍️)

**Comment by clouedoc** [comment]
This text has been written with keymapping

I am writing! 

Let's hope that they release fast 🙏 
Side-effect of kindaVim: making blind people actually able to use their computers

**Comment by godbout** [comment]
> This text has been written with keymapping

> I am writing!

🥃️

> Let's hope that they release fast 🙏

they said it should lend in 107: https://chromiumdash.appspot.com/schedule
seems it's like end October? 😨️

> Side-effect of kindaVim: making blind people actually able to use their computers

wait. you haven't seen Wooshy's release that is coming in one or two hours 😂️

**Comment by godbout** [comment]
wait, actually i need your help for Arc. would be a pity to release a version that doesn't work.

shitting a mini app for macOS 12 and adding in comment below.

**Comment by godbout** [comment]
so what you need to do:

1. quit Shortcat because it's gonna blast the special AX attributes on Arc
2. quit Arc
3. start Arc again
4. try Wooshy on Arc. it shouldn't work
5. start the app above
6. pray that it works on macOS12
7. send thoughts also, not just prayers
8. on the left side, AXEnhancedUserInterface. click on SET and go click on Arc. i think you have one sec to go click. wait maybe one or two sec
9. try again Wooshy on Arc. see if it works. if it works, please report. if it doesn't go to 10
10. on the left side, AXManual. click on SET and go click on Arc etc etc.
11. try again Wooshy on Arc. see if it works. report.

thanks!

**Comment by clouedoc** [comment]
The shady app works!

AXEnhancedUserInterface: OK
I'm testing Manual in case it helps

**Comment by clouedoc** [comment]
Posting a screenshot for archiving purposes

![Capture d’écran 2022-08-22 à 18 56 19](https://user-images.githubusercontent.com/13921610/185976899-4628c046-f6c6-4992-94c6-387d9d049e1a.png)

**Comment by godbout** [comment]
> The shady app works!

i'm learning from my mistakes 😎️

> AXEnhancedUserInterface: OK I'm testing Manual in case it helps

if it works with Enhanced then it's ok. usually Manual is for Electron.

**Comment by godbout** [comment]
> Posting a screenshot for archiving purposes
> 
> ![Capture d’écran 2022-08-22 à 18 56 19](https://user-images.githubusercontent.com/13921610/185976899-4628c046-f6c6-4992-94c6-387d9d049e1a.png)

it's beautiful tho.

but to confirm, once you SET the Enhanced, then you could ping the UI Elements with Wooshy right?

**Comment by godbout** [comment]
a18 out: https://github.com/godbout/Wooshy.docs/releases/tag/1.a18

fingers crossed for Arc.

**Comment by clouedoc** [comment]
IT WORKS!

**Comment by godbout** [comment]
![images](https://user-images.githubusercontent.com/121373/186060885-4f516a49-aa8f-44fa-ba82-4329a60b7196.jpeg)

**Comment by godbout** [comment]
new release to make Wooshy work even better with Arc: https://github.com/godbout/Wooshy.docs/releases/tag/31
