### ISSUE TITLE
Feature request: Distributed notifications on enter/exit

### ISSUE THREAD

**Issue by jannis-baum** [godbout/Wooshy.docs#64]
Like [in kV](https://github.com/godbout/kindaVim.docs/issues/100), sending [distributed notifications](https://developer.apple.com/documentation/foundation/distributednotificationcenter) on enter/exit of The Input would open up new possibilities for using Wooshy in conjunction with other tools such as Karabiner Elements & Hammerspoon. See https://github.com/godbout/Wooshy.docs/issues/63#issuecomment-1226069763 for a use case example.

**Comment by godbout** [comment]
any preferred name for the DNs? i'm trying to stick with what Apple does but they don't have something proper for windows. there's `hide/unhide` for applications tho.

some ideas i have, in order of preference for me:

1. WooshyInputDidAppear/Disappear
2. WooshyInputDidUnhide/Hide
3. WooshyInputDidShow/Hide

i mostly prefer 1. because it sounds cute and magical 😂️

**Comment by godbout** [comment]
> 1. WooshyInputDidAppear/Disappear

sorry, already decided. it's just too cute.

**Comment by godbout** [comment]
done in a20: https://github.com/godbout/Wooshy.docs/releases/tag/1.a20

there's automated tests but tbh i think i didn't tested manually through an external app. let me know if it doesn't work properly.

**Comment by jannis-baum** [comment]
With Hammerspoon (`~/.hammerspoon/init.lua`) set up like this

```lua
wooshyAppearWatcher = hs.distributednotifications.new(function(name, object, userInfo)
    hs.printf('appear')
end, 'WooshyInputDidAppear')
wooshyAppearWatcher:start()

wooshyDisappearWatcher = hs.distributednotifications.new(function(name, object, userInfo)
    hs.printf('disappear')
wooshyDisappearWatcher:start()
```

it looks like Wooshy sends the `appear` at the correct time, but the `disappear` is always sent right before the `appear` instead of when disappearing (you can open the console with the print output through the Menubar Item's menu at "Console...")

**Comment by jannis-baum** [comment]
😂😂🤦 looks like it's still too early. Gonna go have a coffee

**Comment by godbout** [comment]
and it's Monday so you're double-excused.
