### ISSUE TITLE
Feature Request: Drag and drop

### ISSUE THREAD

**Issue by aaronrolls** [godbout/Wooshy.docs#68]
Not sure if this is possible, but it would be great to be able to select something, and then type the location you want it to be moved to. 

Considering the lack of keys on the keyboard, I think the only way to continue to add more features is to have leading characters like "~^#" and so forth.

I imagine it looking something like this 

Type in Wooshy: "~issues"
Enter
Type in Wooshy: "some input field"

link to https://github.com/godbout/Wooshy.docs/issues gets dragged to that field.

**Comment by godbout** [comment]
i guess we're taking the #FreeTheMouse quite seriously here.

i think for extra features i'll have to be careful and add slowly to not make the whole UX a mess and too complicated.
i guess that i could dig into this for after v1 (but of course it might be than in 2 hours i start looking into it coz it's cool. you never know.)

**Comment by godbout** [comment]
just an idea, what about if `command c` would copy the link if the type of Target is, well, a link? https://github.com/godbout/Wooshy.docs/issues/51

**Comment by aaronrolls** [comment]
> just an idea, what about if command c would copy the link if the type of Target is, well, a link? https://github.com/godbout/Wooshy.docs/issues/51

I didn't even consider another type of shortcut other than `something enter`. `command c` for link copying is great idea.

**Comment by godbout** [comment]
been playing with this:

https://user-images.githubusercontent.com/121373/188324848-4c0cbad0-93f2-46af-b39b-4139103ee84b.mp4

usual issues not foreseen. so after playing with it i'm finding that several times i would like to copy what's on the screen but behind it's actually a link. you can see a video all the links that are on the GitHub page. probably a lot of them you may not have thought at first that they were links.

so i'm thinking. what about using 1) `command c` to copy what is shown on the screen and 2) `option command c` for more specific metadata behind, i.e. in the case of the link, well, the link. `option command c` is what is used all over macOS to `copy with style` when available. so on the one hand it's a common shortcut, and on the other hand well it would override the default `copy with style` (but i'm not even sure that would be possible to do that with Wooshy anyways).

any thoughts?

**Comment by godbout** [comment]
could use `shift command c`. i don't think it's common, but personally i usually find it more natural that `option` or `control`.

**Comment by godbout** [comment]
> could use `shift command c`. i don't think it's common, but personally i usually find it more natural that `option` or `control`.

plus there's already `shift command enter` to move without clicking. plus by default you Woosh with `shift command space`. maybe those extra keyboard shortcut should be configurable in the Settings.

**Comment by godbout** [comment]
should The Input hide after copying? yes no? an option?

**Comment by aaronrolls** [comment]
I think `option` `command` `c` is the better option but it would be good to be able to customize it. 

As for hiding, it definitely should by default. You could add it as an option, but I would expect it hide.

**Comment by godbout** [comment]
> I think `option` `command` `c` is the better option

:GIF_of_cat_slapping_human_face:

why?

**Comment by godbout** [comment]
unfortunately it works but only with `shift command c` ☹️

https://user-images.githubusercontent.com/121373/188387976-0e278ae1-6054-4e1d-b9c3-a86d76728b59.mp4

**Comment by aaronrolls** [comment]
No worries. Looks great!

**Comment by godbout** [comment]
OH COME ON YOU NEED TO PUSH HARDER!

now it's just `shift command c` coz it's hardcoded. 

when you said `option` is better you meant for you or there's an objective rationale behind?

i can add customization. i like to keep it minimal tho. less tests to write. less opportunities to fuck up. so maybe a drop-down like the `escape` in kV? but only `shift` and `option` choosable? more? combinations? :cry:

**Comment by godbout** [comment]
during my swim i thought "hey, what about allowing any modifier?" and i think this is pretty good. 

`command c` to copy what's on the screen. add another modifier to copy the metadata instead. 

may also only allow if no text is selected within The Input itself.

**Comment by godbout** [comment]
copy done in a21: https://github.com/godbout/Wooshy.docs/releases/tag/1.a21

not planning to do anything particular for any kinda of drag and drop, at least not for now. closing. please reopen if you need.

**Comment by godbout** [comment]
https://www.youtube.com/watch?v=m2KpXtRnQWE&t

**Comment by aaronrolls** [comment]
That is amazing! Nice work.

**Comment by aaronrolls** [comment]
That I so useful! I already know it is going to be one of those things I never new I needed.

**Comment by godbout** [comment]
GREAT! glad i could combine the two ideas 😅️

**Comment by godbout** [comment]
btw metadata are going to depend on the type of field. i'm handling specifically links, radiobuttons, checkboxes and buttons for the moment. the rest will have to be fine-tuned over time. if you find some UI Elements that feel funky, let me know and i'll have a look.

**Comment by godbout** [comment]
also, copying when The Input is empty is not done. i'm planning at a later stage to copy the UI Element at the mouse position. like how you click at the mouse position when The Input is empty. but that requires more work. so i left it for later.
