### ISSUE TITLE
Any chance for a non-subscription license?

### ISSUE THREAD

**Issue by gasparschott** [godbout/Wooshy.docs#70]
This project looks really good.

**Comment by godbout** [comment]
nope, sorry. not worth for me to have a one time purchase. i work on and give responsive support on my apps daily. plus they're dealing with unstable/uncontrollable parts of macOS that require constant work.

if for you the sub is a no-go for you, i'd suggest:
1) trying some alternatives: https://github.com/godbout/Wooshy.docs#alternatives
2) find a way to crack it (not necessary for now, license is not required until v1)

good luck!
