### ISSUE TITLE
not working on Sunsama

### ISSUE THREAD

**Issue by roelvangils** [godbout/Wooshy.docs#71]
![leonardo-dicaprio-reaction-gif](https://user-images.githubusercontent.com/103744/188867434-9bf4a257-b67f-4fad-8692-d11f634e4949.gif)

**Comment by godbout** [comment]
will add for next release. thanks!

**Comment by godbout** [comment]
added in a22. sorry, took a week. the multiple monitors support is tougher than expected. so i'm releasing a22 now so that Sunsama is out.
