### ISSUE TITLE
Support for selecting text (if selectable)

### ISSUE THREAD

**Issue by roelvangils** [godbout/Wooshy.docs#74]
I have another idea! :) Now that you implemented support for <kbd>⌘+C</kbd>, I think a shortcut for _selecting_ the matched text would also make a lot of sense. Only if the text is selectable, of course. And I suggest <kbd>⌘+A</kbd> for that ("Select all"). It would make it easy to select entire paragraphs of text based on a snippet of text you search for in that paragraph.

Currently, <kbd>⌘+A</kbd> selects all the text in Wooshy's search field, but I think that is not needed (it is standard behaviour). I mean, I have never used it there.

Thanks for considering! Open for discussion as well!

**Comment by godbout** [comment]
what's the use case?

currently you can press `enter` to reach the input field, and press `command a`. so that would save one keystroke? not sure i'm getting it sorry.

**Comment by roelvangils** [comment]
I'm not talking about selecting the text in input fields but selecting paragraphs of text. Currently, when you <kbd>Enter</kbd>, Wooshy will click the target. That is great. But I would like to use Wooshy as a way to quickly select found text (anywhere) and then do something with it, such as cutting it or sending it to another application (such as Alfred or DeepL or something).

**Comment by godbout** [comment]
also, what should be copied? paragraph? whole text? as usual, that's more complicated than it sounds. need specifics.

**Comment by godbout** [comment]
btw this is already achievable, although not natively within Wooshy: https://github.com/godbout/Wooshy.docs/issues/51#issuecomment-1223800660

**Comment by godbout** [comment]
@roelvangils isn't this issue superseded by https://github.com/godbout/Wooshy.docs/issues/151?

**Comment by roelvangils** [comment]
Absolutely! Let me close this one 🙂
