### ISSUE TITLE
Not working with: BusyCal

### ISSUE THREAD

**Issue by januz** [godbout/Wooshy.docs#75]
Great project! I can't seem to get Wooshy to work with BusyCal (alternative calendar application). A few main elements are selectable but none of the calendar entries, etc.

**Comment by godbout** [comment]
will check. might be an Electron app and/or an app that requires special Accessibility attributes to work. will keep you posted.

**Comment by godbout** [comment]
had a quick check, i don't think it's an Electron, or it requires some special attributes. seems more at first glance that the scrollable calendar itself is not Accessible, so Wooshy can't get the data.

i've checked with `Shortcat` and `Homerow`, two apps that work similarly, and they both don't get the calendar either. i'll research more, but that's a bad sign.

**Comment by januz** [comment]
Argh, thanks for looking into it! I hope that it'll be possible somehow.

**Comment by godbout** [comment]
confirmed by the devs: "Yes BusyCal is not accessible in the way you would think as it does not use standard controls."

nothing more we can do here sorry.

**Comment by januz** [comment]
Okay, thanks for trying!
