### ISSUE TITLE
Not working with: RStudio

### ISSUE THREAD

**Issue by januz** [godbout/Wooshy.docs#76]
I am not able to access elements in [RStudio](https://www.rstudio.com/products/rstudio/download/). Would be great if you could look into this. Thank you!

**Comment by godbout** [comment]
the Desktop version?: https://www.rstudio.com/products/rstudio/

thoughts and prayers.

**Comment by januz** [comment]
Yep!

**Comment by godbout** [comment]
there's good news and bad news:

* bad news: RStudio seems to be a mess: 1) they're changing name: https://www.rstudio.com/blog/rstudio-is-becoming-posit/ Wooshy will use the bundle identifier to know whether it needs to blast the app with special AX attributes, so the name change may be important. 2) they're switching from the current frontend to an Electron: https://support.rstudio.com/hc/en-us/articles/5773239924375-RStudio-Electron-Preview-Release-Notes
* good news: Wooshy can handle Electron, as long as the app expose its UI Elements
* you can get
 Wooshy to work somehow with the current qt frontend by enabling the Accessibility in RStudio's Preferences. see below:

![Screenshot 2022-09-15 at 01 12 08](https://user-images.githubusercontent.com/121373/190219274-c4920027-385d-48f1-ab04-dd4419aa4d72.png)

**Comment by januz** [comment]
Very cool, thanks so much!!

**Comment by godbout** [comment]
i'll leave this open so that i have a reminder that things are changing on their side but please feel free to ping me if you see that it stops working. hopefully they'll get stable ultimately and we can get this to work permanently.

**Comment by godbout** [comment]
actually i'm gonna close it as there is nothing to do now. letting it open i keep coming back to it... we can reopen once RStudio enforces their Electron use.
