### ISSUE TITLE
Show shortcuts like `homerow`

### ISSUE THREAD

**Issue by januz** [godbout/Wooshy.docs#77]
I have been playing with both `homerow` and `Wooshy` at the same time to see which works better for me. Unfortunately, the answer is both/neither.

I think that `homerow`'s approach of showing quick navigation shortcuts on activation is the quickest way for me to click something. Maybe it's because I'm just more used to this approach because I have been using it in my browser (using Surfingkeys) for a long time and am thus pretty quick with typing the shortcuts to execute the click. But it just seems like the more natural way for me because typically I'm looking at an interface and know immediately what I want to click. Bringing up `homerow` is one action, typing the shortcut for the element that I'm already looking at is the second, and I'm done. With `Wooshy`, I have to invest more "cognitive energy" as I have to semantically describe the element I want to click, then potentially still navigate between different candidates. It just takes way longer for me which somewhat defeats the purpose of replacing the mouse.

Don't get me wrong, I really like your fuzzy search algorithm and *in some situations* I think this is way superior to just displaying the shortcuts and, generally, your algorithm for detecting clickable elements is better than `homerow`'s but in most cases I feel like the shortcut solution is sufficient and way quicker, i.e., feels more like actually replacing a click. I assume that you have very specific reasons why you implemented Wooshy the way it is (and, as I said, the functionality you built is great for specific needs) but if I could wish for the perfect combination of features, it would be a combination of `Wooshy` and `homerow`:

- bringing up `Wooshy` immediately shows the quick navigation shortcuts (basically as if `Wooshy` was opened, `*` was typed, and instead of just showing all elements they would have a quick navigation shortcut associated with them)
- pressing `return`, hides the elements and opens the fuzzy search window to allow to select and click elements in the `Wooshy` search and drill-down way
- pressing `esc` closes `Wooshy` in either mode
- (alternatively, the standard `Wooshy` way and the `homerow` way could be associated with two different shortcuts which I'm currently doing while testing both applications but I think integrating it into one would be preferable)

Sorry for asking for such a drastic change but I thought I'd ask as, at least for me personally, this would be the perfect application. Thanks so much!

**Comment by godbout** [comment]
> I think that `homerow`'s approach of showing quick navigation shortcuts on activation is the quickest way for me to click something. Maybe it's because I'm just more used to this approach because I have been using it in my browser (using Surfingkeys) for a long time and am thus pretty quick with typing the shortcuts to execute the click. But it just seems like the more natural way for me because typically I'm looking at an interface and know immediately what I want to click. Bringing up `homerow` is one action, typing the shortcut for the element that I'm already looking at is the second, and I'm done. With `Wooshy`, I have to invest more "cognitive energy" as I have to semantically describe the element I want to click, then potentially still navigate between different candidates. It just takes way longer for me which somewhat defeats the purpose of replacing the mouse.

we have different experiences. when i tried Vimac, the problem i had was 1) it was too slow (Homerow seems to be an improvement at this) 2) the most important, it required some cognitive work from me to decipher the hints, even more because they may not be the same every time.

so i built Wooshy. Wooshy is for me a better fit (of course), because i don't have to wait for the hints to decipher. i can just type what i know i want to type. it definitely takes more typing. it also definitely takes more skills: you need to type correctly. but at least, in my case, i'm not _waiting_ for something to show up, and i don't have to decipher something. it works better for me. but it's a matter of taste and needs, definitely..

if you need less typing, Vimac is better. maybe have a look at Shortcat too?: https://shortcat.app it has both the hints and the typing.

> Don't get me wrong, I really like your fuzzy search algorithm and _in some situations_ I think this is way superior to just displaying the shortcuts and, generally, your algorithm for detecting clickable elements is better than `homerow`'s but in most cases I feel like the shortcut solution is sufficient and way quicker, i.e., feels more like actually replacing a click. I assume that you have very specific reasons why you implemented Wooshy the way it is (and, as I said, the functionality you built is great for specific needs) but if I could wish for the perfect combination of features, it would be a combination of `Wooshy` and `homerow`:

JFI, the fuzzy search will be upgraded later. the idea is to have different "presets": Launchbar fuzzy, Alfred fuzzy, Wooshy fuzzy, etc. still, no hints for Wooshy sorry.


> * bringing up `Wooshy` immediately shows the quick navigation shortcuts (basically as if `Wooshy` was opened, `*` was typed, and instead of just showing all elements they would have a quick navigation shortcut associated with them)
> * pressing `return`, hides the elements and opens the fuzzy search window to allow to select and click elements in the `Wooshy` search and drill-down way
> * pressing `esc` closes `Wooshy` in either mode
> * (alternatively, the standard `Wooshy` way and the `homerow` way could be associated with two different shortcuts which I'm currently doing while testing both applications but I think integrating it into one would be preferable)
> 
> Sorry for asking for such a drastic change but I thought I'd ask as, at least for me personally, this would be the perfect application. Thanks so much!

sorry, kinda skipping some stuff. but there's also some points in the roadmap, like keeping Wooshy activated even when you select something, or making it "not steal the focus", so that you can basically click anywhere. currently it steals the focus, so some popovers, notifications etc. will disappear when you activate Wooshy. probably not what you're talking about but feeling like mentioning it.

**Comment by godbout** [comment]
i highly recommend you checking out [Shortcat](https://shortcat.app) as this seems to be doing what you're looking for: the hints.

**Comment by januz** [comment]
Oh, wow, I was using `Shortcat` back in the day but thought that development had stopped. Didn't know that they picked it up again, thank you!

**Comment by godbout** [comment]
yeah, back from the dead recently.

**Comment by godbout** [comment]
@januz any reason why you would want to use Wooshy over Homerow/Shortcat as they're having the hints and Wooshy doesn't? out of curiosity. i think most people would prefer Homerow (less typing).

**Comment by godbout** [comment]
> @godbout  After you told me that `Shortcat` had been revived, I installed it and am now using it over `Wooshy` because it has both the hints and search capability.

interesting. i would have expected `Homerow` over `Shortcat` for the hints. `Homerow` doesn't steal focus, which is great for some popovers, and there's more and more coming with Ventura. `Shortcat`, like `Wooshy`, steals the focus and those popovers then disappear. `Homerow` is pretty fast now too.

**Comment by godbout** [comment]
anyways, thanks for taking the time to answer @januz. gonna close this one as hints are not gonna happen in `Wooshy`. and if i really decide to go for it one day, then i'll just use `Homerow` 😂️
