### ISSUE TITLE
double click

### ISSUE THREAD

**Issue by godbout** [godbout/Wooshy.docs#81]
currently the `double click` is not available in Wooshy. most of the time you can generate a `double click` in macOS with `command o`. like you use Wooshy to target a file in Finder, then `command o` to open it. but still. would be nice to have the `double click` from Wooshy.

now, what's the best way?
1. quick double return?
2. another special key combination? which one?

**Comment by roelvangils** [comment]
Double ↩️ would be cool (if it doesn't delay the default single ↩️).

**Comment by godbout** [comment]
> Double ↩️ would be cool (if it doesn't delay the default single ↩️).

very good point. thanks.

**Comment by parssak** [comment]
Maybe a keybinding option for this could be nice? I think some might want the ability to do "cmd+return" or "shift+return"

Keep up the great work btw, one of the quickest purchases i've ever made for a mac app by far

**Comment by godbout** [comment]
> Maybe a keybinding option for this could be nice? I think some might want the ability to do "cmd+return" or "shift+return"

i'm thinking the same. personally i barely use the double click, but i do need it sometimes. the `command return` and `shift return` are already used for other clicks. also `shift command return` to just move the mouse without clicking. so maybe a whole `control option command return` for the double click? or a more simple but maybe weird `fn return`?

> Keep up the great work btw, one of the quickest purchases i've ever made for a mac app by far

great! yes, more coming. daily work on kV, Wooshy and Scrolla. glad you're enjoying it. and the good thing with the sub is that if one day you don't need Wooshy anymore, don't enjoy it or find a better app, you can just drop easily!

**Comment by godbout** [comment]
added in v3: https://github.com/godbout/Wooshy.docs/releases/tag/3
