### ISSUE TITLE
add Wooshy to Homebrew? :)

### ISSUE THREAD

**Issue by johnaaron-git** [godbout/Wooshy.docs#85]
It looks like kindaVim is already on homebrew, I'd love it if Wooshy was too.

Cheers!

**Comment by godbout** [comment]
hello Sir!

yes, it's totally in the plans. will start with stable v1, which should be the next release, and should happen in maybe two weeks? the very valid rationale behind this decision is that Homebrew Casks differentiate alpha/beta from stable and it's a little extra work and i'm very lazy.

**Comment by godbout** [comment]
Wooshy is in Homebrew since yesterday ✌️enjoy

**Comment by johnaaron-git** [comment]
Thank you! Is it under a custom tap? I get this when I search for it directly on Brew.sh:

<img width="644" alt="Screenshot 2022-12-19 at 5 13 28 PM" src="https://user-images.githubusercontent.com/32317888/208470371-80ad74bd-d116-43cb-9145-9b569ed0ff7f.png">

**Comment by johnaaron-git** [comment]
Actually never mind; it can be located by navigating directly to its cask page here (it must not be indexed yet):

https://formulae.brew.sh/cask/wooshy

**Comment by godbout** [comment]
@johnaaron-git it's a Cask, not part of brew core. Apps are in Homebrew Casks.

<img width="227" alt="Screenshot 2022-12-20 at 00 17 16" src="https://user-images.githubusercontent.com/121373/208471146-892bcce4-5d0c-4fc1-adb3-4c56e05372f4.png">

they've changed stuff recently to make things easier, so you can install it just with `brew install wooshy`.

**Comment by godbout** [comment]
> Actually never mind; it can be located by navigating directly to its cask page here (it must not be indexed yet):
> 
> https://formulae.brew.sh/cask/wooshy

oh my bad. you're right. it should still show up in the Homebrew page search. so yeah, probably not indexed yet.

**Comment by lougreenwood** [comment]
Seems it's still not indexed? I also don't see `scrolla` when I search for that either... :(

**Comment by godbout** [comment]
> Seems it's still not indexed? I also don't see `scrolla` when I search for that either... :(

what do you mean? i can install them both from Homebrew:

<img width="779" alt="Screenshot 2023-01-11 at 23 24 39" src="https://user-images.githubusercontent.com/121373/211845658-4d9cd769-cf8a-4523-ac25-52fa0c6dc596.png">

**Comment by godbout** [comment]
searchable too:

<img width="692" alt="Screenshot 2023-01-11 at 23 25 59" src="https://user-images.githubusercontent.com/121373/211845897-c5d728a9-32d0-4327-8ef4-0d4db81c0764.png">

**Comment by godbout** [comment]
they answered. search is from Algolia. doesn't always work/or work like people expect. better use the `brew` command line, you'll get updated data.
