### ISSUE TITLE
not working on WhatsApp

### ISSUE THREAD

**Issue by johnaaron-git** [godbout/Wooshy.docs#86]
Wooshy doesn't detect any text or buttons (electron app :( )

The inspector doesn't seem find anything inside the window either.

**Comment by godbout** [comment]
@johnaaron-git Electron apps need to be individually supported (if you wanna keep Wooshy small and efficient), but WhatsApp has been supported for a long time. see below:

![Uploading Screenshot 2022-11-23 at 16.13.52.png…]()

can you try hiding and activating WhatsApp again (or closing and opening again). Wooshy will detect and set the Electron shit attributes to the app, and you should be able to grab the UI Elements.

**Comment by johnaaron-git** [comment]
I'm using Whatsapp Desktop from the App Store, if that's affecting anything. My UI looks slightly different than yours.

Here's a clip reproducing the issue (fresh restart -> open wooshy -> open whatsapp).

https://user-images.githubusercontent.com/32317888/203784517-78d4576c-d024-462f-99ec-8c855b670c8c.mov

**Comment by godbout** [comment]
ah. that's it. the App Store version has a different bundle identifier. i need to add it explicitly. thanks. will do, and release in a few days probably.

**Comment by godbout** [comment]
or maybe it's due to the fact that you have a "fluent french speakers" group. too many baguettes.

**Comment by godbout** [comment]
added in 1b5: https://github.com/godbout/Wooshy.docs/releases/tag/1.b5

**Comment by johnaaron-git** [comment]
Confirmation that WhatsApp for Desktop via the App Store now works perfectly for me :) Thank you!

**Comment by godbout** [comment]
enjoy.
