### ISSUE TITLE
Option Return creates a new line in Wooshy input

### ISSUE THREAD

**Issue by aaronrolls** [godbout/Wooshy.docs#9]
Option Return should Option Click, but instead it creates a new line in the Wooshy input box.
![CleanShot2022-07-26at08 00 31](https://user-images.githubusercontent.com/47949221/180864411-47c93277-2642-48e7-bddd-8618d1a61c5f.png)

**Comment by godbout** [comment]
any chance you're still on a1? this should come with a2: https://github.com/godbout/Wooshy.docs/releases/tag/1a.2

**Comment by aaronrolls** [comment]
Sorry, yes I was. I did not know there was a newer version. It works now.

**Comment by aaronrolls** [comment]
Works in 1a2
