### ISSUE TITLE
Multi-display support?

### ISSUE THREAD

**Issue by adamjrichman** [godbout/Wooshy.docs#90]
Seems this only works on the primary display? Any way to add multiple monitor support? Also I prefer Wooshy over Homebrew, etc. simply because the app update changelog is the funniest (and the privacy policy is the clearest). Keep it up! :)

**Comment by godbout** [comment]
the multiple monitor support was added end of September, in a23: https://github.com/godbout/Wooshy.docs/releases/tag/1.a23

what's not working?

a video below, with the macOS Settings that apps have Separate Spaces: 

https://user-images.githubusercontent.com/121373/205806559-ebc2bb46-f59c-4c6a-b324-79bd69a9a4b2.mp4

the macOS Settings that apps SHARE the Space is also supported, but requires to logout to activate and i'm too lazy 😂️

what's the exact issue you're seeing? no Target highlighted? can't click? click at the wrong place?

also, Wooshy can only grab info of the frontmost window, that is the window that is currently activated. if you need to bring any other window that is behind to the front, you can use this [Alfred Workflow](https://github.com/godbout/Wooshy.docs#need-to-bring-any-macos-window-to-the-foreground) (of course, if you use Alfred, and if you're the proud owner of the PowerPack.)

**Comment by godbout** [comment]
> Wooshy only controls the currently active window. Hope that helps :)

yes, maybe the confusion is here. **Wooshy will only target the frontmost active window**. that's for several reasons, including the fact that you can't click on windows that are BEHIND others. there would be ways to grab ALL THE VISIBLE WINDOWS available, and filter out the parts that are not visible etc. but that'd slow enough that it would make Wooshy's UX not attractive at all.

there's many ways to bring windows to the foreground, included the Alfred Workflow i've shared above (and that i am too lazy to paste again 😂️)

**Comment by adamjrichman** [comment]
Crisis averted y'all. Yes, that was the confusion (active app). And it's actually probably better this way. 

And I have, like many folks, abandoned my Alfred PowerPack for [Raycast](raycast.com). :)

**Comment by godbout** [comment]
> And I have, like many folks, abandoned my Alfred PowerPack for [Raycast](raycast.com). :)

hopefully Raycast has some extensions to bring any window to the foreground ✌️
