### ISSUE TITLE
App becomes unresponsive when you quickly change background transparency

### ISSUE THREAD

**Issue by pugson** [godbout/Wooshy.docs#94]
Seems like it can only be reproduced when dragging the slider. Video doesn't show it but when the app freezes the cursor changes to a beachball.

https://user-images.githubusercontent.com/6843656/208316073-36a1710e-09a2-489c-b405-f5f70f5454ff.mp4

<img width="644" alt="CleanShot 2022-12-17 at 07 54 07 PM@2x" src="https://user-images.githubusercontent.com/6843656/208316045-edfa15e3-22ad-441b-8d3a-554a71adbdde.png">

**Comment by godbout** [comment]
been ok for me most of the time but i have been able to reproduce at least once. will investigate. thanks!

**Comment by pugson** [comment]
for context i am using multiple displays

**Comment by godbout** [comment]
thanks for the precision. most probably not related to that. there's tricks to be done when using Wooshy on itself, for various reasons. in all the apps (kV, Wooshy and Scrolla) there's a need to handle things differently when the app is activated on itself (again, for various reasons). so there may be an issue there. will definitely look for a way to fix that.

**Comment by godbout** [comment]
fix in v3: https://github.com/godbout/Wooshy.docs/releases/tag/3
but now the background slider will only show the background changes, and it will not show any fake Targets. can't get both to work at the same time without rewriting some parts of the engine. not worth just for those Settings display tricks.
