### ISSUE TITLE
not working on Things

### ISSUE THREAD

**Issue by Soft-Bred** [godbout/Wooshy.docs#97]
App: https://culturedcode.com/things/

**Comment by Soft-Bred** [comment]
Ah my mistake, it does work, just not... with the names of the cells.

https://user-images.githubusercontent.com/60551230/208601171-e749679a-9b0d-4ff6-b2d4-b4499615b4c2.mp4

**Comment by godbout** [comment]
yes. you can check what can targets a UI Element by using The Inspector. activate Wooshy and move the mouse (yeah i know) to a UI Element. you'll get a list of terms that match a target. in the case of Things, those cells have nothing, excepting the role given automatically by macOS. it's a pity. i've asked the Things guy if they could enhanced that but they said it's not a priority.

**Comment by Soft-Bred** [comment]
damn, what a shame, thanks for looking into it though <3

**Comment by godbout** [comment]
> damn, what a shame, thanks for looking into it though <3

yep, sure. that's a point of the sub too. spending time contacting devs to make their apps more accessible, and therefore working better with my own apps.
